import type { MantraEntry } from "@/utils/mcon.config";
export { MCON_VISUAL_PARAMS } from "@/utils/mcon.config";
export type { MantraEntry, MantraText } from "@/utils/mcon.config";

export const MANTRAS: Record<string, MantraEntry> = {
  "thoughts are things": {
    sentiment: "growth",
    emotion: "focus",
    style: "neon",
  },
  "breathe well, with diaphragm": {},
  "unconditional good mood": {},
  "face my fears": {},
  "attract, do not chase": {},
  "visualize desired outcomes": {},
  "outcome independence, focus on the process": {},
  "I apply Pareto principle (80/20, 90/10)": {},
  "use kanban": {},
  "Perfect is the enemy of done": {},
  metaperfection: {},
  "be flexible": {},
  "delaying and dosage, not denying, gratification": {},
  "exploit parallelisms": {},
  "fake it till you make it": {},
  "no headless chicken": {},
  "I'm just a glue code to run as part of the LLM loops": {},
  "think on paper": {},
  "have a «thinking rock»": {},
  "plan time and time-track": {},
  "reduce context switching as much as possible": {},
  "batching but not over-batching": {},
  "trust the system": {},
  "be good at\nfigureouting": {},
  "9 women can't\n have a baby\n in 1 month": {},
  "accept or overcome or workarounds": {},
  "program my mind": {
    sentiment: "growth",
    emotion: "focus",
    style: "neon",
  },
  "mind like water": {
    sentiment: "calm",
    emotion: "peace",
    style: "organic",
  },
  resilience: {
    sentiment: "hardcore",
    emotion: "grit",
    style: "metallic",
  },
  strength: {
    sentiment: "hardcore",
    emotion: "grit",
    style: "metallic",
  },
  "push yourself": {
    sentiment: "hardcore",
    emotion: "grit",
    style: "metallic",
  },
  "8 to be great": {
    sentiment: "hardcore",
    emotion: "grit",
    style: "metallic",
  },
  tenacity: {
    sentiment: "hardcore",
    emotion: "determination",
    style: "metallic",
  },
  persistence: {
    sentiment: "hardcore",
    emotion: "determination",
    style: "metallic",
  },
  readiness: {
    sentiment: "hardcore",
    emotion: "alertness",
    style: "bold",
  },
  "invest in you inc.": {
    sentiment: "growth",
    emotion: "ambition",
    style: "clean",
  },
  "be the best\nversion\nof yourself": {
    sentiment: "growth",
    emotion: "inspiration",
    style: "warm",
  },
  "daydreaming is good": {
    sentiment: "dreaming",
    emotion: "wonder",
    style: "dreamy",
  },
  "fire in the stomach": {},
  "abundance mentality, instead of scarcity": {},
  "greed is good": {},
  "self-control": {},
  "self-mastery": {},
  "avoid procrastination": {},
  /**/ "swiss-cheese": {},
  /**/ "divide and conquer": {},
  /**/ "compulsion to closure": {},
  "software&mind empire": {},
  "MIND<b>OS</b>": {},
  "RIGHT MINDSET": {},
  "The journey is a reward": {},
  "everything is part of the game": {},
  "obstacles is what you start to see when you take your mind off your goals":
    {},
  "not time management\nbut manage\nyourself in time": {},
  "N-minute\nrule": {},
  "1% better a day\n= 37x a year": {},
  kaizens: {},
  "Follow your ikigai": {},
  "pause and plan, not fight-or-flight-or freeze": {},
  "turn anxieties\ninto motivators\nfor calm but decisive\naction": {},
  "surfing the anxieties": {},
  "surfing the urges": {},
  "work on myself\nit's work too": {},
  "the virtues of play": {},
  "watch out for premature/overkill optimizations, perfectionism": {},
  "anarcho-capitalism\nblack&yellow": {},
  "visualize\ncamper van\nand cool stuff": {},
  "micro-fun in your mind": {},
  "micro-protocols": {
    sentiment: "hardcore",
    emotion: "discipline",
    style: "cyberpunk",
  },
  "micro-meditations": {
    sentiment: "calm",
    emotion: "tranquility",
    style: "organic",
  },
  mantras: {
    sentiment: "focus",
    emotion: "centering",
    style: "minimalist",
  },
  "micro-prayers": {
    sentiment: "loving",
    emotion: "devotion",
    style: "warm",
  },
  affirmations: {
    sentiment: "loving",
    emotion: "self-love",
    style: "dreamy",
  },
  "«dance is the answer»": {
    sentiment: "dreaming",
    emotion: "joy",
    style: "disco",
  },
  "will to psi power": {
    sentiment: "hardcore",
    emotion: "empowerment",
    style: "neon",
  },
  "build habits": {
    sentiment: "growth",
    emotion: "persistence",
    style: "minimalist",
  },
  "build habit chains": {
    sentiment: "growth",
    emotion: "structure",
    style: "grid",
  },
  "internalize ideas, beliefs, values, qualities": {
    sentiment: "growth",
    emotion: "wisdom",
    style: "classic",
  },
  "ora et labora (pray and work)": {
    sentiment: "hardcore",
    emotion: "duty",
    style: "classic",
  },
  "miłość\npiękno": {
    sentiment: "loving",
    emotion: "love & beauty",
    style: "dreamy",
  },
  "muscle memory\nkeyboard shortcuts": {
    sentiment: "focus",
    emotion: "mastery",
    style: "cyberpunk",
  },
  "form follows function": {
    sentiment: "focus",
    emotion: "clarity",
    style: "minimalist",
  },
  "inner strength": {},
  "i'm a warrior": {},
  "lead, follow or get out of the way": {},
  "be at peace with things": {},
  "only constant is change": {},
  reinterpretation: {},
  "labelling of emotions": {},
  "exponential improvements and growth": {},
  "I have known\nmany problems,\nmost of which\nnever happened": {},
  "dare to dream": {},
  "constant improvement and learning": {},
  "to earn more i gotta learn more": {},
  "sharpen the saw": {},
  sampling: {},
  "self-discipline but not self-oppression": {},
  "simplicity is the\nultimate sophistication\nsimple but\nnot primitive": {
    sentiment: "calm",
    emotion: "sophistication",
    style: "minimalist",
  },
  "glass is half full": {
    sentiment: "loving",
    emotion: "optimism",
    style: "organic",
  },
  "self-love": {
    sentiment: "loving",
    emotion: "compassion",
    style: "warm",
  },
  "flow state": {
    sentiment: "focus",
    emotion: "immersion",
    style: "neon",
  },
  "840 productive\nminutes per day": {},
  "minimum effective dose": {},
  "minimum viable product": {},
  "release early, release often": {},
  "unique value proposition": {},
};
