import type { MantraEntry } from '@/utils/mcon.config';
export { MCON_VISUAL_PARAMS } from '@/utils/mcon.config';
export type { MantraEntry, MantraText } from '@/utils/mcon.config';

export const MANTRAS: Record<string, MantraEntry> = {
  'program my mind for success and to avoid unnecessary suffering': {
    sentiment: 'growth',
    emotion: 'focus',
    style: 'neon',
  },
  'program my mind early, program often': {},
  '7 levels of Consciousness': {},
  '<b>Creator</b> Consciousness': {},
  'Non-attachment': {},
  'Practice non-judgement': {},
  'WTP Music': {},
  'Pławię się w swojej świadomości': {},
  'Be honest with myself, instead of in denial or ignorance': {
    examples:
      'Am I running like a headless chicken and constantly changing music, instead of steady focus?',
  },
  'Make positive associations between positive things': {
    examples: 'Work and providing value in capitalism',
  },
  'Be in here and now': {},
  'Get into the space between thoughts': {
    // sourse: Deepak Chopra
  },
  "Don't dramatize": {},
  'Smile :-)': {},
  'Agape - unconditional love': {},
  'Find beauty and love everywhere': {},
  'Gratefulness - best state to be ready to receive': {},
  'thoughts are things': {
    sentiment: 'growth',
    emotion: 'focus',
    style: 'neon',
  },
  'mental anchors including posters': {
    categories: { motivation: {} },
  },
  "Lose the inner heaviness. It's all a fancy game. Play the game.": {
    categories: { motivation: {} },
  },
  'Internal locus of control': {},
  'breathe well, with diaphragm': {
    categories: { motivation: {} },
  },
  'unconditional good mood': {
    categories: { motivation: {} },
  },
  'face my fears to flush them out': {
    categories: { motivation: {} },
  },
  'attract, do not chase': {},
  'When a decision is not clear, choose randomly. Especially if I can change the choice.': {},
  'visualize desired outcomes': {
    categories: { motivation: {} },
  },
  'outcome independence, focus on the process, effort and the journey, adventure, experiences':
    {
      categories: { motivation: {} },
    },
  'I apply Pareto principle (80/20, 90/10)': {},
  'Use Kanban': {
    categories: { motivation: { intensityPercent: 50 } },
  },
  'patience and patient progress': {
    categories: { motivation: {} },
  },
  'Perfect is the enemy of done': {
    categories: { motivation: {} },
  },
  'believe in myself': {
    categories: { motivation: {} },
  },
  'Confident body language': {},
  'Meta-meta-perfection': {
    categories: { motivation: {} },
  },
  'be flexible': {},
  'delaying and dosage and right kind, not denying, of gratification': {},
  'exploit parallelisms': {
    categories: { motivation: {} },
  },
  'fake it till you make it': {},
  'no headless chicken': {},
  "I'm just a glue code to run as part of the LLM loops": {},
  'think on paper': {},
  'have a «thinking rock»': {},
  'plan time (but not over-plan) and time-track': {},
  'reduce context switching as much as possible': {},
  'batching but not over-batching': {},
  'trust the system': {},
  'be good at\nfigureouting': {},
  "9 women can't\n have a baby\n in 1 month": {},
  'accept or overcome or workarounds/hacks': {},
  'mind like water': {
    sentiment: 'calm',
    emotion: 'peace',
    style: 'organic',
  },
  'Resilience (as part of the game)': {
    sentiment: 'hardcore',
    emotion: 'grit',
    style: 'metallic',
  },
  'Strength (as part of the game)': {
    sentiment: 'hardcore',
    emotion: 'grit',
    style: 'metallic',
  },
  'Push yourself (as part of the game)': {
    sentiment: 'hardcore',
    emotion: 'grit',
    style: 'metallic',
  },
  '8 to be great': {
    sentiment: 'hardcore',
    emotion: 'grit',
    style: 'metallic',
  },
  tenacity: {
    sentiment: 'hardcore',
    emotion: 'determination',
    style: 'metallic',
  },
  persistence: {
    sentiment: 'hardcore',
    emotion: 'determination',
    style: 'metallic',
  },
  readiness: {
    sentiment: 'hardcore',
    emotion: 'alertness',
    style: 'bold',
  },
  'invest in you inc.': {
    sentiment: 'growth',
    emotion: 'ambition',
    style: 'clean',
  },
  'be the best\nversion\nof yourself': {
    sentiment: 'growth',
    emotion: 'inspiration',
    style: 'warm',
  },
  'daydreaming is good': {
    sentiment: 'dreaming',
    emotion: 'wonder',
    style: 'dreamy',
  },
  'Capitalism - provide value': {},
  'fire in the stomach': {},
  'Abundance mentality, instead of scarcity': {},
  'greed is good (but things are ephemeral, so practice non-attachment)': {},
  'self-control': {},
  'self-mastery': {},
  'avoid procrastination': {},
  /**/ 'swiss-cheese': {},
  /**/ 'divide and conquer': {},
  /**/ 'compulsion to closure': {},
  'software&mind&content empire': {},
  'MIND<b>OS</b>': {},
  'RIGHT MINDSET': {},
  'The journey is a reward': {},
  'Go with the flow. Bez spiny.': {},
  'A journey of a thousand miles begins with one step': {},
  'everything is part of the game': {},
  'obstacles is what you start to see when you take your mind off your goals':
    {},
  'not time management\nbut manage\nyourself&energy in time': {},
  'N-minute\nrule': {},
  '1% better a day\n= 37x a year': {},
  kaizens: {
    categories: { efficiency: {} },
  },
  'Follow your ikigai': {
    categories: { motivation: {}, inspiration: {} },
  },
  'pause and plan (but not over-plan), not fight-or-flight-or freeze': {},
  'turn anxieties\ninto motivators\nfor calm but decisive\naction': {},
  'surfing the anxieties': {},
  'surfing the urges': {},
  'Feeling of positive urgency': {},
  'do mental katas (e.g. surfing the x)': {},
  "work on myself\nit's work too": {},
  'the virtues of play': {},
  'watch out for premature/overkill optimizations, perfectionism': {},
  'anarcho-capitalism\nblack&yellow': {},
  'visualize camper van and MacBook Pro and cool stuff, BD Parties': {
    categories: { motivation: {}, inspiration: {} },
  },
  'find life bottlenecks (e.g. getting up - reflux?) and optimize': {},
  'praise the Subconscious Mind after even small successes': {},
  'micro-fun in your mind': {},
  'micro-celebrations': {},
  'micro-gratifications': {},
  'micro-rituals': {},
  'micro-optimizations': {},
  'micro-protocols': {
    sentiment: 'hardcore',
    emotion: 'discipline',
    style: 'cyberpunk',
  },
  'micro-breaks': {},
  'micro-meditations': {
    sentiment: 'calm',
    emotion: 'tranquility',
    style: 'organic',
  },
  'micro-mindfulness': {},
  'micro-visualizations': {},
  'micro-Visualizations & micro-planning': {},
  'micro-gratitudes': {},
  mantras: {
    sentiment: 'focus',
    emotion: 'centering',
    style: 'minimalist',
  },
  'micro-prayers': {
    sentiment: 'loving',
    emotion: 'devotion',
    style: 'warm',
  },
  affirmations: {
    sentiment: 'loving',
    emotion: 'self-love',
    style: 'dreamy',
  },
  '«dance is the answer»': {
    sentiment: 'dreaming',
    emotion: 'joy',
    style: 'disco',
  },
  'will to psi power': {
    sentiment: 'hardcore',
    emotion: 'empowerment',
    style: 'neon',
    categories: { motivation: {} },
  },
  'build habits': {
    sentiment: 'growth',
    emotion: 'persistence',
    style: 'minimalist',
    categories: { efficiency: {} },
  },
  'build habit chains': {
    sentiment: 'growth',
    emotion: 'structure',
    style: 'grid',
    categories: { efficiency: {} },
  },
  '<b>Internalize</b> ideas, beliefs, values, qualities': {
    sentiment: 'growth',
    emotion: 'wisdom',
    style: 'classic',
  },
  'ora et labora (pray and work)': {
    sentiment: 'hardcore',
    emotion: 'duty',
    style: 'classic',
    categories: { motivation: {} },
  },
  'miłość\npiękno': {
    sentiment: 'loving',
    emotion: 'love & beauty',
    style: 'dreamy',
    categories: { motivation: {} },
  },
  'muscle memory\nkeyboard shortcuts': {
    sentiment: 'focus',
    emotion: 'mastery',
    style: 'cyberpunk',
  },
  'if LLMs lack discipline, the fault lies with their commander': {
    sentiment: 'focus',
    emotion: 'mastery',
    style: 'cyberpunk',
  },
  'form follows function': {
    sentiment: 'focus',
    emotion: 'clarity',
    style: 'minimalist',
  },
  'inner strength': {},
  "i'm a warrior": {},
  'i am driven': {},
  'no-games-day challenges': {},
  'think from long perspective - how much I can achieve, given compounding and exponential growth':
    {
      categories: { motivation: {} },
    },
  'lead, follow or get out of the way': {},
  'be at peace with things': {},
  'only constant is change': {},
  'every minute spent in planning, saves N minutes in execution': {},
  'Kefisatz Haderach': {},
  'TRAIN SELF-DISCIPLINE and SELF-ESTEEM, like a muscle': {},
  'Billy Carson Formula': {},
  reinterpretation: {},
  'Not problems, but <b>challenges</b>': {},
  'Look at challenges as a beautiful intricate beings': {},
  'labelling of emotions and situations': {},
  'exponential improvements and growth': {},
  'I have known\nmany problems,\nmost of which\nnever happened': {
    author: 'Mark Twain',
  },
  'dare to dream': {},
  'Do spine traction for back pain': {},
  'happiness advantage': {},
  'Positive Qualia Advantage': {},
  'Quick prototyping also has psychological value': {},
  'constant improvement and learning': {},
  'To earn more I gotta learn more': {},
  'Master AI Content Generation.': {},
  'sharpen the saw': {},
  'sampling of gratifications (even as visualizations)': {},
  'self-discipline but not self-oppression': {},
  'simplicity is the ultimate sophistication. simple but not primitive.': {
    sentiment: 'calm',
    emotion: 'sophistication',
    style: 'minimalist',
  },
  'glass is half full': {
    sentiment: 'loving',
    emotion: 'optimism',
    style: 'organic',
  },
  'self-love (but malignant narcissism)': {
    sentiment: 'loving',
    emotion: 'compassion',
    style: 'warm',
  },
  'Focus on the what and why, let the Universe handle the "how".': {},
  'Flow State - Discipline and Surrender': {
    sentiment: 'focus',
    emotion: 'immersion',
    style: 'neon',
  },
  '840 productive\nminutes per day': {},
  'minimum effective dose': {},

  'minimum viable product': {},
  "Put on different hats. Don't think only like a developer.": {},
  'Use the best tool(s) for the job(s).': {},
  'release early, release often': {},
  'unique value proposition': {},
  'have to -> want to': {},
  'towards-state': {},
  'Zapierdalac. Be like Elon and Martin and RH and Tudor.': {},
  'Regrets minimization principle': {},
  'What gets measured, gets managed': { author: 'Peter Drucker' },
};
