// Real field recordings for nature ambience, sourced from freesound.org.
// Metadata here is the single source of truth for both playback (sound-engine.ts)
// and the in-app attributions popover (components/sound-attributions-popover.tsx) —
// keeping them in sync so a CC-BY credit can never silently go missing.
//
// `kind` is an arbitrary string id (not a fixed enum) since this list runs into
// the hundreds — see AmbienceCategory below for how the Soundscape UI groups them.
export type AmbienceKind = string;

export type SoundLicense = 'CC0' | 'CC-BY-4.0';

export type AmbienceCategory =
  | 'Nature'
  | 'Water'
  | 'Weather'
  | 'Animals'
  | 'Urban'
  | 'Interior'
  | 'Transport'
  | 'Cozy'
  | 'Meditation';

export interface AmbienceSource {
  kind: AmbienceKind;
  label: string;
  file: unknown; // require()'d audio asset module
  title: string;
  author: string;
  sourceUrl: string;
  license: SoundLicense;
  category: AmbienceCategory;
}

export const AMBIENCE_SOURCES: AmbienceSource[] = [
  {
    kind: 'forest',
    label: 'Forest',
    file: require('@/assets/sounds/forest-ambience.mp3'),
    title: 'Windy Autumn Forest Soundscape 2',
    author: 'Porphyr',
    sourceUrl: 'https://freesound.org/people/Porphyr/sounds/209339/',
    license: 'CC-BY-4.0',
    category: 'Nature',
  },
  {
    kind: 'waterfall',
    label: 'Waterfall',
    file: require('@/assets/sounds/waterfall-ambience.mp3'),
    title: 'Ambiance_Waterfall_Loop_04',
    author: 'Nox_Sound',
    sourceUrl: 'https://freesound.org/people/Nox_Sound/sounds/511075/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'waves',
    label: 'Water waves',
    file: require('@/assets/sounds/waves-ambience.mp3'),
    title: 'Ocean Waves Loop - Day',
    author: 'Koops',
    sourceUrl: 'https://freesound.org/people/Koops/sounds/586117/',
    license: 'CC-BY-4.0',
    category: 'Water',
  },
  {
    kind: 'rain',
    label: 'Rain',
    file: require('@/assets/sounds/rain-ambience.mp3'),
    title: 'Looping Rain On Skylight Foley Texture',
    author: 'deadrobotmusic',
    sourceUrl: 'https://freesound.org/people/deadrobotmusic/sounds/663947/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'thunderstorm',
    label: 'Thunderstorm',
    file: require('@/assets/sounds/thunderstorm-ambience.mp3'),
    title: 'Thunderstorm with rain (loop)',
    author: 'VKProduktion',
    sourceUrl: 'https://freesound.org/people/VKProduktion/sounds/704603/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'campfire',
    label: 'Campfire',
    file: require('@/assets/sounds/campfire-ambience.mp3'),
    title: 'fire-crackling.wav',
    author: 'jmehlferber',
    sourceUrl: 'https://freesound.org/people/jmehlferber/sounds/370938/',
    license: 'CC0',
    category: 'Cozy',
  },
  {
    kind: 'river',
    label: 'River stream',
    file: require('@/assets/sounds/river-ambience.mp3'),
    title: 'Relaxing river stream running water seamless loop',
    author: 'steaq',
    sourceUrl: 'https://freesound.org/people/steaq/sounds/548767/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'wind',
    label: 'Wind',
    file: require('@/assets/sounds/wind-ambience.mp3'),
    title: 'Howling Wind Ambience',
    author: 'DBlover',
    sourceUrl: 'https://freesound.org/people/DBlover/sounds/405601/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'crickets',
    label: 'Night crickets',
    file: require('@/assets/sounds/crickets-ambience.mp3'),
    title: 'Night Crickets Ambience on Rural Property',
    author: 'OwlStorm',
    sourceUrl: 'https://freesound.org/people/OwlStorm/sounds/320145/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'cave',
    label: 'Cave drips',
    file: require('@/assets/sounds/cave-ambience.mp3'),
    title: 'Ambiance_Atmosphere_Cave_Loop_Stereo',
    author: 'Nox_Sound',
    sourceUrl: 'https://freesound.org/people/Nox_Sound/sounds/553080/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'coffeeShop',
    label: 'Coffee shop',
    file: require('@/assets/sounds/coffee-shop-ambience.mp3'),
    title: 'coffee shop ambience',
    author: 'waweee',
    sourceUrl: 'https://freesound.org/people/waweee/sounds/370973/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'train',
    label: 'Train',
    file: require('@/assets/sounds/train-ambience.mp3'),
    title: 'Train Rumble and Rattle',
    author: 'ProductionNow',
    sourceUrl: 'https://freesound.org/s/455045/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'traffic',
    label: 'City traffic',
    file: require('@/assets/sounds/traffic-ambience.mp3'),
    title: 'City Traffic Ambience',
    author: 'DataJuggler',
    sourceUrl: 'https://freesound.org/people/DataJuggler/sounds/750144/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'windChimes',
    label: 'Wind chimes',
    file: require('@/assets/sounds/wind-chimes-ambience.mp3'),
    title: 'Wind Chimes (No Background Noise)',
    author: 'mooncubedesign',
    sourceUrl: 'https://freesound.org/people/mooncubedesign/sounds/440929/',
    license: 'CC0',
    category: 'Meditation',
  },
  {
    kind: 'snow',
    label: 'Snow storm',
    file: require('@/assets/sounds/snow-ambience.mp3'),
    title: 'Howling winter storm ambient sounds',
    author: 'DBlover',
    sourceUrl: 'https://freesound.org/people/DBlover/sounds/505999/',
    license: 'CC0',
    category: 'Weather',
  },
  // --- Bulk-sourced CC0 recordings (freesound.org, filtered to Creative Commons 0 + short duration) ---
  {
    kind: 'fs-537793',
    label: 'Jungle',
    file: require('@/assets/sounds/bulk-alien-world-jungle-creatures-sci-fi-sfx--537793.mp3'),
    title: 'Alien World Jungle Creatures Sci-fi SFX Ambience 201004_0056_01.wav',
    author: 'szegvari',
    sourceUrl: 'https://freesound.org/people/szegvari/sounds/537793/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-479553',
    label: 'Jungle 2',
    file: require('@/assets/sounds/bulk-r15-77-jungle-night-wav-479553.mp3'),
    title: 'R15-77-Jungle Night.wav',
    author: 'craigsmith',
    sourceUrl: 'https://freesound.org/people/craigsmith/sounds/479553/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-333225',
    label: 'Jungle 3',
    file: require('@/assets/sounds/bulk-bako-national-park-borneo-island-rain-fo-333225.mp3'),
    title: 'Bako National Park, Borneo Island, Rain Forest Ambience daytime 01.10.2013 Roland R-26 OMNI Mics.wav',
    author: 'gladkiy',
    sourceUrl: 'https://freesound.org/people/gladkiy/sounds/333225/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-547690',
    label: 'Swamp',
    file: require('@/assets/sounds/bulk-swamp-ambience-mp3-547690.mp3'),
    title: 'Swamp Ambience.mp3',
    author: 'RyanKingArt',
    sourceUrl: 'https://freesound.org/people/RyanKingArt/sounds/547690/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-479575',
    label: 'Swamp 2',
    file: require('@/assets/sounds/bulk-r28-19-swamp-or-jungle-background-wav-479575.mp3'),
    title: 'R28-19-Swamp or Jungle Background.wav',
    author: 'craigsmith',
    sourceUrl: 'https://freesound.org/people/craigsmith/sounds/479575/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-516927',
    label: 'Swamp 3',
    file: require('@/assets/sounds/bulk-swamp-at-night-with-crickets-and-cicadas-516927.mp3'),
    title: 'swamp at night with crickets and cicadas.mp3',
    author: 'mariethompson',
    sourceUrl: 'https://freesound.org/people/mariethompson/sounds/516927/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-697217',
    label: 'Desert wind',
    file: require('@/assets/sounds/bulk-looping-gentle-wind-ambience-on-an-open--697217.mp3'),
    title: 'Looping Gentle Wind Ambience on an Open Desert Plain.wav',
    author: 'dhallcomposer',
    sourceUrl: 'https://freesound.org/people/dhallcomposer/sounds/697217/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-540837',
    label: 'Desert wind 2',
    file: require('@/assets/sounds/bulk-temple-cave-desert-storm-540837.mp3'),
    title: 'Temple Cave Desert Storm',
    author: 'szegvari',
    sourceUrl: 'https://freesound.org/people/szegvari/sounds/540837/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-557552',
    label: 'Desert wind 3',
    file: require('@/assets/sounds/bulk-dark-sahara-egypt-557552.mp3'),
    title: 'Dark Sahara Egypt',
    author: 'szegvari',
    sourceUrl: 'https://freesound.org/people/szegvari/sounds/557552/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-288899',
    label: 'Mountain wind',
    file: require('@/assets/sounds/bulk-rocky-mountain-outdoors-wind-and-birds-288899.mp3'),
    title: 'Rocky Mountain Outdoors:  wind and birds',
    author: 'petebuchwald',
    sourceUrl: 'https://freesound.org/people/petebuchwald/sounds/288899/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-223960',
    label: 'Mountain wind 2',
    file: require('@/assets/sounds/bulk-night-ambience-in-japanese-forest-strong-223960.mp3'),
    title: 'Night ambience in Japanese forest, strong wind, some rain drops on cement',
    author: 'tcpp',
    sourceUrl: 'https://freesound.org/people/tcpp/sounds/223960/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-855955',
    label: 'Mountain wind 3',
    file: require('@/assets/sounds/bulk-04-birds-stereo-855955.mp3'),
    title: '04 - Birds_stereo',
    author: 'Nordliecht',
    sourceUrl: 'https://freesound.org/people/Nordliecht/sounds/855955/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-729234',
    label: 'Meadow',
    file: require('@/assets/sounds/bulk-meadow-in-summer-1-wav-729234.mp3'),
    title: 'Meadow in summer 1.WAV',
    author: 'fi2lcallpeace',
    sourceUrl: 'https://freesound.org/people/fi2lcallpeace/sounds/729234/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-529573',
    label: 'Meadow 2',
    file: require('@/assets/sounds/bulk-meadow-with-many-insects-chirps-atmo-fie-529573.mp3'),
    title: 'Meadow with many insects chirps atmo field recording',
    author: 'Garuda1982',
    sourceUrl: 'https://freesound.org/people/Garuda1982/sounds/529573/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-274498',
    label: 'Meadow 3',
    file: require('@/assets/sounds/bulk-nature-wav-274498.mp3'),
    title: 'nature.wav',
    author: 'llexi',
    sourceUrl: 'https://freesound.org/people/llexi/sounds/274498/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-705953',
    label: 'Marsh frogs',
    file: require('@/assets/sounds/bulk-frog-swamp-m4a-705953.mp3'),
    title: 'Frog Swamp.m4a',
    author: 'MushroomMan123',
    sourceUrl: 'https://freesound.org/people/MushroomMan123/sounds/705953/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-569543',
    label: 'Marsh frogs 2',
    file: require('@/assets/sounds/bulk-many-frogs-at-night-in-marsh-wav-569543.mp3'),
    title: 'Many Frogs at Night in Marsh.wav',
    author: 'bmacphail',
    sourceUrl: 'https://freesound.org/people/bmacphail/sounds/569543/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-812191',
    label: 'Marsh frogs 3',
    file: require('@/assets/sounds/bulk-frogs-various-heavy-wetland-ambience-at--812191.mp3'),
    title: 'Frogs - Various; Heavy Wetland Ambience at Dusk',
    author: 'TheKingOfGeeks360',
    sourceUrl: 'https://freesound.org/people/TheKingOfGeeks360/sounds/812191/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-666760',
    label: 'Owl at night',
    file: require('@/assets/sounds/bulk-owl-at-night-666760.mp3'),
    title: 'owl at night',
    author: 'opalmirage',
    sourceUrl: 'https://freesound.org/people/opalmirage/sounds/666760/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-719558',
    label: 'Owl at night 2',
    file: require('@/assets/sounds/bulk-forest-at-night-ambience-719558.mp3'),
    title: 'Forest At Night Ambience',
    author: 'fribergmusic2024',
    sourceUrl: 'https://freesound.org/people/fribergmusic2024/sounds/719558/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-745681',
    label: 'Owl at night 3',
    file: require('@/assets/sounds/bulk-young-typical-owl-calling-745681.mp3'),
    title: 'Young typical owl calling',
    author: 'Patrick_Corra',
    sourceUrl: 'https://freesound.org/people/Patrick_Corra/sounds/745681/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-504641',
    label: 'Underwater',
    file: require('@/assets/sounds/bulk-underwater-ambience-504641.mp3'),
    title: 'Underwater Ambience',
    author: 'Fission9',
    sourceUrl: 'https://freesound.org/people/Fission9/sounds/504641/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-567347',
    label: 'Underwater 2',
    file: require('@/assets/sounds/bulk-underwater-ambience-wav-567347.mp3'),
    title: 'Underwater ambience.wav',
    author: 'Merrick079',
    sourceUrl: 'https://freesound.org/people/Merrick079/sounds/567347/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-675196',
    label: 'Underwater 3',
    file: require('@/assets/sounds/bulk-s21-24-underwater-metal-clanking-wav-675196.mp3'),
    title: 'S21-24 Underwater metal clanking.wav',
    author: 'craigsmith',
    sourceUrl: 'https://freesound.org/people/craigsmith/sounds/675196/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-735401',
    label: 'Glacier ice',
    file: require('@/assets/sounds/bulk-ice-fracture-roots-or-growing-plants-735401.mp3'),
    title: 'Ice - Fracture, roots or growing plants',
    author: 'Vrymaa',
    sourceUrl: 'https://freesound.org/people/Vrymaa/sounds/735401/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-519566',
    label: 'Geyser',
    file: require('@/assets/sounds/bulk-lakesoundscape3-519566.mp3'),
    title: 'LakeSoundscape3',
    author: 'Nivatius',
    sourceUrl: 'https://freesound.org/people/Nivatius/sounds/519566/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-222642',
    label: 'Geyser 2',
    file: require('@/assets/sounds/bulk-spouting-horn-kauai-wav-222642.mp3'),
    title: 'Spouting Horn Kauai.wav',
    author: 'tec_studio',
    sourceUrl: 'https://freesound.org/people/tec_studio/sounds/222642/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-323426',
    label: 'Light drizzle',
    file: require('@/assets/sounds/bulk-light-rain-and-crickets-323426.mp3'),
    title: 'light rain and crickets',
    author: 'seth-m',
    sourceUrl: 'https://freesound.org/people/seth-m/sounds/323426/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-626578',
    label: 'Light drizzle 2',
    file: require('@/assets/sounds/bulk-light-relaxing-rain-sound-626578.mp3'),
    title: 'Light Relaxing rain sound',
    author: 'AdrianoAnjos',
    sourceUrl: 'https://freesound.org/people/AdrianoAnjos/sounds/626578/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-849916',
    label: 'Light drizzle 3',
    file: require('@/assets/sounds/bulk-light-rain-inside-a-car-driver-seat-849916.mp3'),
    title: 'Light Rain inside a car, driver seat',
    author: 'leocb',
    sourceUrl: 'https://freesound.org/people/leocb/sounds/849916/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-500146',
    label: 'Foghorn',
    file: require('@/assets/sounds/bulk-foghorn-wav-500146.mp3'),
    title: 'foghorn.WAV',
    author: 'phonoflora',
    sourceUrl: 'https://freesound.org/people/phonoflora/sounds/500146/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-361408',
    label: 'Foghorn 2',
    file: require('@/assets/sounds/bulk-early-morning-summer-ambience-361408.mp3'),
    title: 'Early morning summer ambience',
    author: 'richwise',
    sourceUrl: 'https://freesound.org/people/richwise/sounds/361408/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-735350',
    label: 'Hurricane wind',
    file: require('@/assets/sounds/bulk-wind-hurricane-typhoon-storm-735350.mp3'),
    title: 'Wind - Hurricane Typhoon Storm',
    author: 'Vrymaa',
    sourceUrl: 'https://freesound.org/people/Vrymaa/sounds/735350/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-425141',
    label: 'Creek',
    file: require('@/assets/sounds/bulk-small-brook-loopable-field-recording-wal-425141.mp3'),
    title: 'Small Brook Loopable (field recording walk with daughter - rec 4).wav',
    author: 'gis_sweden',
    sourceUrl: 'https://freesound.org/people/gis_sweden/sounds/425141/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-608141',
    label: 'Creek 2',
    file: require('@/assets/sounds/bulk-river-flow-loop-608141.mp3'),
    title: 'River Flow Loop',
    author: 'EminYILDIRIM',
    sourceUrl: 'https://freesound.org/people/EminYILDIRIM/sounds/608141/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-231536',
    label: 'Creek 3',
    file: require('@/assets/sounds/bulk-creek-06-loop-231536.mp3'),
    title: 'Creek 06 (loop)',
    author: 'VKProduktion',
    sourceUrl: 'https://freesound.org/people/VKProduktion/sounds/231536/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-529663',
    label: 'Lake shore',
    file: require('@/assets/sounds/bulk-by-the-lake-529663.mp3'),
    title: 'By the lake',
    author: 'tender_sounds',
    sourceUrl: 'https://freesound.org/people/tender_sounds/sounds/529663/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-757115',
    label: 'Lake shore 2',
    file: require('@/assets/sounds/bulk-ocean-waves-ambience-757115.mp3'),
    title: 'Ocean Waves Ambience',
    author: 'jcdeegs123',
    sourceUrl: 'https://freesound.org/people/jcdeegs123/sounds/757115/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-500169',
    label: 'Lake shore 3',
    file: require('@/assets/sounds/bulk-lakeside-ambience-500169.mp3'),
    title: 'Lakeside ambience',
    author: 'sad3d',
    sourceUrl: 'https://freesound.org/people/sad3d/sounds/500169/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-195876',
    label: 'Harbor water',
    file: require('@/assets/sounds/bulk-130723-brela-harborjump-r-4824-wav-195876.mp3'),
    title: '130723_Brela_HarborJump_R_4824.wav',
    author: 'blaukreuz',
    sourceUrl: 'https://freesound.org/people/blaukreuz/sounds/195876/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-811407',
    label: 'Fountain',
    file: require('@/assets/sounds/bulk-watrfoun-samsung-galaxy-smartphone-cu-sh-811407.mp3'),
    title: 'WATRFoun-Samsung Galaxy Smartphone, CU_Short Pump Town Center-Water Fountain_Nicholas Judy_TDC',
    author: 'designerschoice',
    sourceUrl: 'https://freesound.org/people/designerschoice/sounds/811407/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-677228',
    label: 'Fountain 2',
    file: require('@/assets/sounds/bulk-sfx-water-fountain-1-mp3-677228.mp3'),
    title: 'sfx_water_fountain_1.mp3',
    author: 'davilca',
    sourceUrl: 'https://freesound.org/people/davilca/sounds/677228/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-677229',
    label: 'Fountain 3',
    file: require('@/assets/sounds/bulk-sfx-water-fountain-2-mp3-677229.mp3'),
    title: 'sfx_water_fountain_2.mp3',
    author: 'davilca',
    sourceUrl: 'https://freesound.org/people/davilca/sounds/677229/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-406496',
    label: 'Quiet library',
    file: require('@/assets/sounds/bulk-public-library-ground-floor-quiet-distan-406496.mp3'),
    title: 'public library ground floor quiet distant voices2 Gaza 2016.wav',
    author: 'kyles',
    sourceUrl: 'https://freesound.org/people/kyles/sounds/406496/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-847110',
    label: 'Quiet library 2',
    file: require('@/assets/sounds/bulk-short-church-bell-ring-with-rural-ambien-847110.mp3'),
    title: 'Short Church Bell Ring with Rural Ambience &amp; Birds (High‑Resolution Snippet) Altenthann – 260303_001',
    author: 'TSP-Talk',
    sourceUrl: 'https://freesound.org/people/TSP-Talk/sounds/847110/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-399824',
    label: 'Quiet library 3',
    file: require('@/assets/sounds/bulk-medium-rain-dropping-on-metal-surface-wa-399824.mp3'),
    title: 'Medium rain dropping on metal surface.wav',
    author: 'BonnyOrbit',
    sourceUrl: 'https://freesound.org/people/BonnyOrbit/sounds/399824/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-450129',
    label: 'Office',
    file: require('@/assets/sounds/bulk-general-fusion-industrial-workshop-offic-450129.mp3'),
    title: 'General Fusion industrial workshop office ambience1 computer room with conversation and heavy workshop bg.wav',
    author: 'kyles',
    sourceUrl: 'https://freesound.org/people/kyles/sounds/450129/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-708140',
    label: 'Office 2',
    file: require('@/assets/sounds/bulk-office-clean-up-amb-2-708140.mp3'),
    title: 'Office clean up-AMB 2',
    author: 'keahnpot',
    sourceUrl: 'https://freesound.org/people/keahnpot/sounds/708140/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-712886',
    label: 'Office 3',
    file: require('@/assets/sounds/bulk-roomambience-mildsoundproofing-1-712886.mp3'),
    title: 'roomAmbience_mildSoundproofing_1',
    author: 'ichitaraaa',
    sourceUrl: 'https://freesound.org/people/ichitaraaa/sounds/712886/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-474740',
    label: 'Busy restaurant',
    file: require('@/assets/sounds/bulk-restaurant-ambience-chatter-474740.mp3'),
    title: 'Restaurant ambience chatter',
    author: 'mycompasstv',
    sourceUrl: 'https://freesound.org/people/mycompasstv/sounds/474740/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-736754',
    label: 'Busy restaurant 2',
    file: require('@/assets/sounds/bulk-dimsum-restaurant-736754.mp3'),
    title: 'DIMSUM_RESTAURANT',
    author: 'eyeseefilm',
    sourceUrl: 'https://freesound.org/people/eyeseefilm/sounds/736754/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-473586',
    label: 'Busy restaurant 3',
    file: require('@/assets/sounds/bulk-people-talking-adults-amp-children-473586.mp3'),
    title: 'People talking (Adults &amp; Children)',
    author: 'Breviceps',
    sourceUrl: 'https://freesound.org/people/Breviceps/sounds/473586/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-729330',
    label: 'Pub chatter',
    file: require('@/assets/sounds/bulk-spacious-bar-ambience-with-music-medium--729330.mp3'),
    title: 'Spacious Bar Ambience With Music, Medium Crowd 02',
    author: 'HECKFRICKER',
    sourceUrl: 'https://freesound.org/people/HECKFRICKER/sounds/729330/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-839104',
    label: 'Pub chatter 2',
    file: require('@/assets/sounds/bulk-mines-a-pint-839104.mp3'),
    title: 'Mines a pint',
    author: 'apintofmild',
    sourceUrl: 'https://freesound.org/people/apintofmild/sounds/839104/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-509951',
    label: 'Pub chatter 3',
    file: require('@/assets/sounds/bulk-irish-pub-ambience-509951.mp3'),
    title: 'Irish Pub Ambience',
    author: 'Talitha5',
    sourceUrl: 'https://freesound.org/people/Talitha5/sounds/509951/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-591235',
    label: 'Airport terminal',
    file: require('@/assets/sounds/bulk-terminal1-wav-591235.mp3'),
    title: 'terminal1.wav',
    author: 'ToXXuS',
    sourceUrl: 'https://freesound.org/people/ToXXuS/sounds/591235/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-319100',
    label: 'Airport terminal 2',
    file: require('@/assets/sounds/bulk-facturaci-n-wav-319100.mp3'),
    title: 'Facturación.WAV',
    author: 'Soojay',
    sourceUrl: 'https://freesound.org/people/Soojay/sounds/319100/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-210786',
    label: 'Airport terminal 3',
    file: require('@/assets/sounds/bulk-quiet-airport-terminal-flac-210786.mp3'),
    title: 'Quiet airport terminal.flac',
    author: 'jrosin',
    sourceUrl: 'https://freesound.org/people/jrosin/sounds/210786/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-451720',
    label: 'Subway station',
    file: require('@/assets/sounds/bulk-underground-train-station-ambience-451720.mp3'),
    title: 'Underground Train Station Ambience',
    author: 'florianreichelt',
    sourceUrl: 'https://freesound.org/people/florianreichelt/sounds/451720/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-154853',
    label: 'Subway station 2',
    file: require('@/assets/sounds/bulk-subway-sub-way-ambience-wav-154853.mp3'),
    title: 'subway sub way ambience.wav',
    author: 'pawsound',
    sourceUrl: 'https://freesound.org/people/pawsound/sounds/154853/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-727838',
    label: 'Subway station 3',
    file: require('@/assets/sounds/bulk-ambience-metro-komsomolskaya-passage-sub-727838.mp3'),
    title: 'ambience, metro, Komsomolskaya, passage, subway, Moscow',
    author: 'AlexanderChe',
    sourceUrl: 'https://freesound.org/people/AlexanderChe/sounds/727838/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-349689',
    label: 'Server room hum',
    file: require('@/assets/sounds/bulk-070916-machine-room-server-rack-fans-3-w-349689.mp3'),
    title: '070916 Machine room server rack fans 3.wav',
    author: 'thaighaudio',
    sourceUrl: 'https://freesound.org/people/thaighaudio/sounds/349689/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-554124',
    label: 'Washing machine',
    file: require('@/assets/sounds/bulk-washing-machine-554124.mp3'),
    title: 'Washing machine',
    author: 'vialgames',
    sourceUrl: 'https://freesound.org/people/vialgames/sounds/554124/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-855523',
    label: 'Washing machine 2',
    file: require('@/assets/sounds/bulk-motors-mixing-water-sloshing-2-855523.mp3'),
    title: 'Motors_Mixing_Water_Sloshing_2',
    author: 'SoundsofTheMachine',
    sourceUrl: 'https://freesound.org/people/SoundsofTheMachine/sounds/855523/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-394269',
    label: 'Washing machine 3',
    file: require('@/assets/sounds/bulk-dishwasher-hum-wav-394269.mp3'),
    title: 'Dishwasher Hum.WAV',
    author: 'TrekkieDude97',
    sourceUrl: 'https://freesound.org/people/TrekkieDude97/sounds/394269/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-633144',
    label: 'Clock ticking',
    file: require('@/assets/sounds/bulk-ticking-clock-looped-633144.mp3'),
    title: 'ticking clock (looped)',
    author: 'igroglaz',
    sourceUrl: 'https://freesound.org/people/igroglaz/sounds/633144/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-154906',
    label: 'Clock ticking 2',
    file: require('@/assets/sounds/bulk-clock-ticking-154906.mp3'),
    title: 'Clock Ticking',
    author: 'unfa',
    sourceUrl: 'https://freesound.org/people/unfa/sounds/154906/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-797574',
    label: 'Clock ticking 3',
    file: require('@/assets/sounds/bulk-tick-tock-pendulum-family-clock-797574.mp3'),
    title: 'Tick-Tock - Pendulum Family Clock',
    author: 'Vrymaa',
    sourceUrl: 'https://freesound.org/people/Vrymaa/sounds/797574/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-700412',
    label: 'Keyboard typing',
    file: require('@/assets/sounds/bulk-typing-on-a-computer-keyboard-700412.mp3'),
    title: 'Typing on a computer keyboard',
    author: 'Vtrmrll',
    sourceUrl: 'https://freesound.org/people/Vtrmrll/sounds/700412/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-754201',
    label: 'Keyboard typing 2',
    file: require('@/assets/sounds/bulk-fast-keyboard-typing-754201.mp3'),
    title: 'Fast keyboard typing',
    author: 'Spacekittycat',
    sourceUrl: 'https://freesound.org/people/Spacekittycat/sounds/754201/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-361639',
    label: 'Keyboard typing 3',
    file: require('@/assets/sounds/bulk-computer-keyboard-typing-snippet-mono-lo-361639.mp3'),
    title: 'Computer keyboard typing snippet mono [loop]',
    author: 'cabled_mess',
    sourceUrl: 'https://freesound.org/people/cabled_mess/sounds/361639/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-537620',
    label: 'Shower',
    file: require('@/assets/sounds/bulk-shower-running-537620.mp3'),
    title: 'Shower running',
    author: 'colorsCrimsonTears',
    sourceUrl: 'https://freesound.org/people/colorsCrimsonTears/sounds/537620/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-644518',
    label: 'Shower 2',
    file: require('@/assets/sounds/bulk-running-shower-644518.mp3'),
    title: 'Running shower',
    author: 'Froey_',
    sourceUrl: 'https://freesound.org/people/Froey_/sounds/644518/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-177726',
    label: 'Air conditioner',
    file: require('@/assets/sounds/bulk-thailand-room-tone-small-quiet-airy-brea-177726.mp3'),
    title: 'Thailand room tone small quiet airy breathy light ventilation air conditioner hum and distant bumps (looped short clip) +distant voices at start.flac',
    author: 'kyles',
    sourceUrl: 'https://freesound.org/people/kyles/sounds/177726/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-413566',
    label: 'Refrigerator hum',
    file: require('@/assets/sounds/bulk-refrigerator-hum-413566.mp3'),
    title: 'Refrigerator Hum',
    author: 'p0lter',
    sourceUrl: 'https://freesound.org/people/p0lter/sounds/413566/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-524598',
    label: 'Refrigerator hum 2',
    file: require('@/assets/sounds/bulk-fridge-buzz-loop-524598.mp3'),
    title: 'Fridge buzz (loop)',
    author: 'Matislav',
    sourceUrl: 'https://freesound.org/people/Matislav/sounds/524598/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-653455',
    label: 'Refrigerator hum 3',
    file: require('@/assets/sounds/bulk-minifridge-no-hum-loop-wav-653455.mp3'),
    title: 'minifridge no hum loop.wav',
    author: 'walllable',
    sourceUrl: 'https://freesound.org/people/walllable/sounds/653455/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-699132',
    label: 'Pond frogs',
    file: require('@/assets/sounds/bulk-kuipto-forrest-dusk-wild-life-crickets-b-699132.mp3'),
    title: 'Kuipto_forrest_dusk_wild_life_Crickets_birds_Bugs_ambience_01.wav',
    author: 'roisin.gleeson',
    sourceUrl: 'https://freesound.org/people/roisin.gleeson/sounds/699132/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-699131',
    label: 'Pond frogs 2',
    file: require('@/assets/sounds/bulk-kuipto-forrest-dusk-wild-life-crickets-b-699131.mp3'),
    title: 'Kuipto_forrest_dusk_wild_life_Crickets_birds_Bugs_ambience_01.wav',
    author: 'roisin.gleeson',
    sourceUrl: 'https://freesound.org/people/roisin.gleeson/sounds/699131/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-687984',
    label: 'Pond frogs 3',
    file: require('@/assets/sounds/bulk-stefan-a-frog-from-poland-687984.mp3'),
    title: 'Stefan, a frog from Poland.',
    author: 'GirlWithSoundRecorder',
    sourceUrl: 'https://freesound.org/people/GirlWithSoundRecorder/sounds/687984/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-746366',
    label: 'Cicadas',
    file: require('@/assets/sounds/bulk-southern-summer-evening-ambience-with-cr-746366.mp3'),
    title: 'Southern Summer Evening Ambience with Crickets 5',
    author: 'RyanKingArt',
    sourceUrl: 'https://freesound.org/people/RyanKingArt/sounds/746366/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-243438',
    label: 'Cicadas 2',
    file: require('@/assets/sounds/bulk-cicada-summer-wav-243438.mp3'),
    title: 'Cicada summer.wav',
    author: 'beansqueso31',
    sourceUrl: 'https://freesound.org/people/beansqueso31/sounds/243438/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-860235',
    label: 'Cicadas 3',
    file: require('@/assets/sounds/bulk-260623-124149-taiwan-alishan-forest-in-j-860235.mp3'),
    title: '260623_124149_Taiwan Alishan Forest in June - Dense Cicada Chorus - Summer Insect Ambience_台灣阿里山6月_全部都是蟬聲',
    author: 'BayTsai',
    sourceUrl: 'https://freesound.org/people/BayTsai/sounds/860235/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-854532',
    label: 'Seagulls',
    file: require('@/assets/sounds/bulk-beach-ambience-1-854532.mp3'),
    title: 'Beach Ambience 1',
    author: 'TheGreenPig321',
    sourceUrl: 'https://freesound.org/people/TheGreenPig321/sounds/854532/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-854533',
    label: 'Seagulls 2',
    file: require('@/assets/sounds/bulk-beach-ambience-2-854533.mp3'),
    title: 'Beach Ambience 2',
    author: 'TheGreenPig321',
    sourceUrl: 'https://freesound.org/people/TheGreenPig321/sounds/854533/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-854534',
    label: 'Seagulls 3',
    file: require('@/assets/sounds/bulk-beach-ambience-3-854534.mp3'),
    title: 'Beach Ambience 3',
    author: 'TheGreenPig321',
    sourceUrl: 'https://freesound.org/people/TheGreenPig321/sounds/854534/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-567523',
    label: 'Farm animals',
    file: require('@/assets/sounds/bulk-farm-chicken-rooster-sheep-210410-0061-w-567523.mp3'),
    title: 'farm_chicken_rooster_sheep_210410_0061.wav',
    author: 'titi2',
    sourceUrl: 'https://freesound.org/people/titi2/sounds/567523/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-467572',
    label: 'Farm animals 2',
    file: require('@/assets/sounds/bulk-pigs-3-467572.mp3'),
    title: 'PIGS - 3',
    author: 'SamuelGremaud',
    sourceUrl: 'https://freesound.org/people/SamuelGremaud/sounds/467572/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-467574',
    label: 'Farm animals 3',
    file: require('@/assets/sounds/bulk-pigs-5-467574.mp3'),
    title: 'PIGS - 5',
    author: 'SamuelGremaud',
    sourceUrl: 'https://freesound.org/people/SamuelGremaud/sounds/467574/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-245691',
    label: 'Airplane cabin',
    file: require('@/assets/sounds/bulk-aeroplane-ambience-01-aif-245691.mp3'),
    title: 'Aeroplane Ambience 01.aif',
    author: 'TicAshfield',
    sourceUrl: 'https://freesound.org/people/TicAshfield/sounds/245691/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'fs-245690',
    label: 'Airplane cabin 2',
    file: require('@/assets/sounds/bulk-aeroplane-ambience-02-aif-245690.mp3'),
    title: 'Aeroplane Ambience 02.aif',
    author: 'TicAshfield',
    sourceUrl: 'https://freesound.org/people/TicAshfield/sounds/245690/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'fs-792889',
    label: 'Airplane cabin 3',
    file: require('@/assets/sounds/bulk-08-landing-plane-annoucement-short-engli-792889.mp3'),
    title: '08. Landing Plane Annoucement Short, English, Polish',
    author: 'VizAion',
    sourceUrl: 'https://freesound.org/people/VizAion/sounds/792889/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'fs-55050',
    label: 'Boat engine',
    file: require('@/assets/sounds/bulk-ferry-boat-engine-loop-wav-55050.mp3'),
    title: 'ferry_boat_engine_loop.wav',
    author: 'suonidigenova',
    sourceUrl: 'https://freesound.org/people/suonidigenova/sounds/55050/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'fs-264864',
    label: 'Boat engine 2',
    file: require('@/assets/sounds/bulk-marine-diesel-engine-264864.mp3'),
    title: 'Marine diesel engine',
    author: 'AugustSandberg',
    sourceUrl: 'https://freesound.org/people/AugustSandberg/sounds/264864/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'fs-394287',
    label: 'Boat engine 3',
    file: require('@/assets/sounds/bulk-speedboat-loop-wav-394287.mp3'),
    title: 'Speedboat Loop.wav',
    author: 'morganpurkis',
    sourceUrl: 'https://freesound.org/people/morganpurkis/sounds/394287/',
    license: 'CC0',
    category: 'Transport',
  },
  {
    kind: 'fs-615441',
    label: 'Wood stove',
    file: require('@/assets/sounds/bulk-burning-bush-615441.mp3'),
    title: 'Burning Bush',
    author: 'InChristAlone',
    sourceUrl: 'https://freesound.org/people/InChristAlone/sounds/615441/',
    license: 'CC0',
    category: 'Cozy',
  },
  {
    kind: 'fs-615146',
    label: 'Tibetan bowl',
    file: require('@/assets/sounds/bulk-tibetan-bowl-with-effect-107bpm-aif-615146.mp3'),
    title: 'tibetan bowl with effect 107bpm.aif',
    author: 'MieliTietty',
    sourceUrl: 'https://freesound.org/people/MieliTietty/sounds/615146/',
    license: 'CC0',
    category: 'Meditation',
  },
  {
    kind: 'fs-653743',
    label: 'Rainy jungle',
    file: require('@/assets/sounds/bulk-peruvian-amazon-birds-frogs-daytime-653743.mp3'),
    title: 'Peruvian Amazon birds frogs daytime',
    author: 'nonamethefish',
    sourceUrl: 'https://freesound.org/people/nonamethefish/sounds/653743/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-860231',
    label: 'Dawn chorus',
    file: require('@/assets/sounds/bulk-260623-055825-taiwan-chiayi-alishan-ogas-860231.mp3'),
    title: '260623_055825_Taiwan Chiayi Alishan Ogasawara Lookout - June Early Morning - Forest Birds &amp; Dawn Ambience_台灣嘉義阿里山小笠原觀景台6月_清晨',
    author: 'BayTsai',
    sourceUrl: 'https://freesound.org/people/BayTsai/sounds/860231/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-518431',
    label: 'Dawn chorus 2',
    file: require('@/assets/sounds/bulk-dawn-lockdown-01-wav-518431.mp3'),
    title: 'Dawn Lockdown_01.wav',
    author: 'subax',
    sourceUrl: 'https://freesound.org/people/subax/sounds/518431/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-853566',
    label: 'Dawn chorus 3',
    file: require('@/assets/sounds/bulk-nightingale-singing-853566.mp3'),
    title: 'Nightingale Singing',
    author: 'hoshisato',
    sourceUrl: 'https://freesound.org/people/hoshisato/sounds/853566/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-179342',
    label: 'Pond ducks',
    file: require('@/assets/sounds/bulk-duck-pond-sounds-with-traffic-wav-179342.mp3'),
    title: 'Duck Pond Sounds with Traffic.wav',
    author: 'lolamadeus',
    sourceUrl: 'https://freesound.org/people/lolamadeus/sounds/179342/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-179343',
    label: 'Pond ducks 2',
    file: require('@/assets/sounds/bulk-duck-pond-sounds-3-wav-179343.mp3'),
    title: 'Duck Pond Sounds 3.wav',
    author: 'lolamadeus',
    sourceUrl: 'https://freesound.org/people/lolamadeus/sounds/179343/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-179344',
    label: 'Pond ducks 3',
    file: require('@/assets/sounds/bulk-duck-pond-sounds-2-wav-179344.mp3'),
    title: 'Duck Pond Sounds 2.wav',
    author: 'lolamadeus',
    sourceUrl: 'https://freesound.org/people/lolamadeus/sounds/179344/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-662095',
    label: 'Night forest',
    file: require('@/assets/sounds/bulk-amb-forest-night-wav-662095.mp3'),
    title: 'amb_forest_night.wav',
    author: 'Dokuta_Gerovv',
    sourceUrl: 'https://freesound.org/people/Dokuta_Gerovv/sounds/662095/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-150175',
    label: 'Night forest 2',
    file: require('@/assets/sounds/bulk-latenightpeepersandcoyotesmarch302012-wa-150175.mp3'),
    title: 'LateNightPeepersandCoyotesMarch302012.wav',
    author: 'kvgarlic',
    sourceUrl: 'https://freesound.org/people/kvgarlic/sounds/150175/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-699141',
    label: 'Night forest 3',
    file: require('@/assets/sounds/bulk-night-breeze-crickets-kuipto-forrest-ade-699141.mp3'),
    title: 'Night_Breeze_Crickets_Kuipto_Forrest_adelaide_Australia_ambience 01.wav',
    author: 'roisin.gleeson',
    sourceUrl: 'https://freesound.org/people/roisin.gleeson/sounds/699141/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-777458',
    label: 'Desert night',
    file: require('@/assets/sounds/bulk-3-cabo-de-la-vella-colombia-night-5-2-23-777458.mp3'),
    title: '3. Cabo de la Vella - Colombia - Night (5/2/23)',
    author: 'delfieldrecordings',
    sourceUrl: 'https://freesound.org/people/delfieldrecordings/sounds/777458/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-400992',
    label: 'Canyon wind',
    file: require('@/assets/sounds/bulk-winter-winds-400992.mp3'),
    title: 'Winter Winds',
    author: 'UrsaDaBear',
    sourceUrl: 'https://freesound.org/people/UrsaDaBear/sounds/400992/',
    license: 'CC0',
    category: 'Nature',
  },
  {
    kind: 'fs-788119',
    label: 'Gentle beach waves',
    file: require('@/assets/sounds/bulk-beach-morning-gentle-waves-soft-sand-788119.mp3'),
    title: 'Beach Morning - Gentle Waves, Soft Sand',
    author: 'RealSquink',
    sourceUrl: 'https://freesound.org/people/RealSquink/sounds/788119/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-852814',
    label: 'Gentle beach waves 2',
    file: require('@/assets/sounds/bulk-002-bfnk-isq-vaguesrivieremuret-20260426-852814.mp3'),
    title: '002_BFNK_ISQ_VaguesRiviereMuret_20260426_Final_96KHz',
    author: 'Biofonik',
    sourceUrl: 'https://freesound.org/people/Biofonik/sounds/852814/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-222752',
    label: 'Rocky stream',
    file: require('@/assets/sounds/bulk-babbling-brook-loop-wav-222752.mp3'),
    title: 'babbling_brook_loop.wav',
    author: 'minian89',
    sourceUrl: 'https://freesound.org/people/minian89/sounds/222752/',
    license: 'CC0',
    category: 'Water',
  },
  {
    kind: 'fs-843108',
    label: 'Aquarium bubbles',
    file: require('@/assets/sounds/bulk-melody-loop-botanica-melody-4-115bpm-843108.mp3'),
    title: 'Melody Loop-Botanica Melody 4-115Bpm',
    author: 'CAT-FOX_ALEX',
    sourceUrl: 'https://freesound.org/people/CAT-FOX_ALEX/sounds/843108/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-637648',
    label: 'Laundromat',
    file: require('@/assets/sounds/bulk-laundromat-ambience-steamy-machines-ratt-637648.mp3'),
    title: 'laundromat ambience steamy machines rattle.flac',
    author: 'kyles',
    sourceUrl: 'https://freesound.org/people/kyles/sounds/637648/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-658324',
    label: 'Laundromat 2',
    file: require('@/assets/sounds/bulk-cloths-dryer-658324.mp3'),
    title: 'Cloths Dryer.',
    author: 'Tom_Kaszuba',
    sourceUrl: 'https://freesound.org/people/Tom_Kaszuba/sounds/658324/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-537812',
    label: 'Laundromat 3',
    file: require('@/assets/sounds/bulk-laundromat-coin-sorting-machine-537812.mp3'),
    title: 'laundromat coin-sorting machine',
    author: 'PostProdDog',
    sourceUrl: 'https://freesound.org/people/PostProdDog/sounds/537812/',
    license: 'CC0',
    category: 'Urban',
  },
  {
    kind: 'fs-753274',
    label: 'Industrial fan',
    file: require('@/assets/sounds/bulk-ac-unit-interior-exhaust-close-perspecti-753274.mp3'),
    title: 'AC Unit, Interior Exhaust Close Perspective 01',
    author: 'HECKFRICKER',
    sourceUrl: 'https://freesound.org/people/HECKFRICKER/sounds/753274/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-753275',
    label: 'Industrial fan 2',
    file: require('@/assets/sounds/bulk-ac-unit-interior-exhaust-close-perspecti-753275.mp3'),
    title: 'AC Unit, Interior Exhaust Close Perspective 02',
    author: 'HECKFRICKER',
    sourceUrl: 'https://freesound.org/people/HECKFRICKER/sounds/753275/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-271096',
    label: 'Industrial fan 3',
    file: require('@/assets/sounds/bulk-industrial-factory-fans-loop-271096.mp3'),
    title: 'Industrial Factory/Fans Loop',
    author: 'IanStarGem',
    sourceUrl: 'https://freesound.org/people/IanStarGem/sounds/271096/',
    license: 'CC0',
    category: 'Interior',
  },
  {
    kind: 'fs-825858',
    label: 'Monastery bells',
    file: require('@/assets/sounds/bulk-monastery-atmosphere-monk-chant-chimes-825858.mp3'),
    title: 'Monastery atmosphere - Monk chant + chimes',
    author: 'Vrymaa',
    sourceUrl: 'https://freesound.org/people/Vrymaa/sounds/825858/',
    license: 'CC0',
    category: 'Meditation',
  },
  {
    kind: 'fs-783719',
    label: 'Monastery bells 2',
    file: require('@/assets/sounds/bulk-casio-melody-loop-ca-70bpm-783719.mp3'),
    title: 'casio-melody-loop ca 70bpm',
    author: 'MieliTietty',
    sourceUrl: 'https://freesound.org/people/MieliTietty/sounds/783719/',
    license: 'CC0',
    category: 'Meditation',
  },
  {
    kind: 'fs-634140',
    label: 'Spa ambience',
    file: require('@/assets/sounds/bulk-meditative-ethno-folk-chill-relax-spa-lo-634140.mp3'),
    title: 'Meditative Ethno Folk Chill Relax Spa Lo-Fi Mood Nature Meditation Atmo Amb Soundscape Cinematic Surround.wav',
    author: 'szegvari',
    sourceUrl: 'https://freesound.org/people/szegvari/sounds/634140/',
    license: 'CC0',
    category: 'Meditation',
  },
  {
    kind: 'fs-805466',
    label: 'Camping tent',
    file: require('@/assets/sounds/bulk-night-crickets-02-805466.mp3'),
    title: 'Night Crickets 02',
    author: 'Vrymaa',
    sourceUrl: 'https://freesound.org/people/Vrymaa/sounds/805466/',
    license: 'CC0',
    category: 'Cozy',
  },
  {
    kind: 'fs-482687',
    label: 'Night insects',
    file: require('@/assets/sounds/bulk-night-time-crickets-distant-dogs-and-tra-482687.mp3'),
    title: 'Night time crickets, distant dogs and traffic ambience.WAV',
    author: 'SukritSen',
    sourceUrl: 'https://freesound.org/people/SukritSen/sounds/482687/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-752865',
    label: 'Night insects 3',
    file: require('@/assets/sounds/bulk-night-ambience-around-zagreb-752865.mp3'),
    title: 'Night ambience around Zagreb',
    author: 'LukaCafuka',
    sourceUrl: 'https://freesound.org/people/LukaCafuka/sounds/752865/',
    license: 'CC0',
    category: 'Animals',
  },
  {
    kind: 'fs-158692',
    label: 'Distant thunder',
    file: require('@/assets/sounds/bulk-distant-thunder-and-rain-from-half-open--158692.mp3'),
    title: 'Distant Thunder and Rain from Half Open Window 1.aif',
    author: 'RutgerMuller',
    sourceUrl: 'https://freesound.org/people/RutgerMuller/sounds/158692/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-486557',
    label: 'Distant thunder 2',
    file: require('@/assets/sounds/bulk-thunder-rumble-ogg-486557.mp3'),
    title: 'thunder.rumble.ogg',
    author: 'xUMR',
    sourceUrl: 'https://freesound.org/people/xUMR/sounds/486557/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-581125',
    label: 'Distant thunder 3',
    file: require('@/assets/sounds/bulk-distant-thunder-4-581125.mp3'),
    title: 'Distant Thunder 4',
    author: 'Fission9',
    sourceUrl: 'https://freesound.org/people/Fission9/sounds/581125/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-797659',
    label: 'Rainy city night',
    file: require('@/assets/sounds/bulk-exterior-night-rain-concrete-sirens-urba-797659.mp3'),
    title: 'Exterior Night Rain - Concrete, Sirens, Urban',
    author: 'SecureSubset',
    sourceUrl: 'https://freesound.org/people/SecureSubset/sounds/797659/',
    license: 'CC0',
    category: 'Weather',
  },
  {
    kind: 'fs-835896',
    label: 'Rainy city night 2',
    file: require('@/assets/sounds/bulk-summer-night-ambience-heat-ac-units-spar-835896.mp3'),
    title: 'Summer Night Ambience – Heat, AC Units, Sparse Traffic',
    author: 'Artem_Zaitsev',
    sourceUrl: 'https://freesound.org/people/Artem_Zaitsev/sounds/835896/',
    license: 'CC0',
    category: 'Weather',
  },
];

export const ATTRIBUTION_REQUIRED_SOUNDS = AMBIENCE_SOURCES.filter((s) => s.license !== 'CC0');

export function resolveAssetUri(mod: unknown): string {
  if (typeof mod === 'string') return mod;
  const asAny = mod as any;
  if (asAny?.default) return resolveAssetUri(asAny.default);
  if (asAny?.uri) return asAny.uri;
  return String(mod);
}
