export type ColorScheme = 'light' | 'dark';

export type ThemeColors = {
  text: string;
  background: string;
  tint: string;
  icon: string;
  tabIconDefault: string;
  tabIconSelected: string;
  surface: string;
  surfaceRaised: string;
  border: string;
  subtleBackground: string;
  subtleBorder: string;
  onTint: string;
};

export type AppThemeId =
  | 'system'
  | 'sunrise'
  | 'yellow'
  | 'lavender'
  | 'sea-glass'
  | 'rose-paper'
  | 'alpine'
  | 'porcelain'
  | 'apricot'
  | 'sakura'
  | 'moss'
  | 'blueprint'
  | 'sand'
  | 'cloud'
  | 'lilac'
  | 'glacier'
  | 'midnight'
  | 'forest'
  | 'indigo-dusk'
  | 'ember'
  | 'deep-ocean'
  | 'obsidian'
  | 'plum'
  | 'aurora'
  | 'cobalt'
  | 'espresso'
  | 'slate'
  | 'ruby'
  | 'jade'
  | 'solarized'
  | 'monochrome';

export type AppTheme = {
  id: Exclude<AppThemeId, 'system'>;
  name: string;
  description: string;
  colorScheme: ColorScheme;
  colors: ThemeColors;
};

export const APP_THEME_IDS = [
  'system',
  'sunrise',
  'yellow',
  'lavender',
  'sea-glass',
  'rose-paper',
  'alpine',
  'porcelain',
  'apricot',
  'sakura',
  'moss',
  'blueprint',
  'sand',
  'cloud',
  'lilac',
  'glacier',
  'midnight',
  'forest',
  'indigo-dusk',
  'ember',
  'deep-ocean',
  'obsidian',
  'plum',
  'aurora',
  'cobalt',
  'espresso',
  'slate',
  'ruby',
  'jade',
  'solarized',
  'monochrome',
] as const satisfies readonly AppThemeId[];

export function isAppThemeId(value: string | null): value is AppThemeId {
  return APP_THEME_IDS.some((themeId) => themeId === value);
}

const orange = '#f97316';

export const APP_THEMES: Record<Exclude<AppThemeId, 'system'>, AppTheme> = {
  sunrise: {
    id: 'sunrise',
    name: 'Sunrise',
    description: 'Warm paper and the Structable orange.',
    colorScheme: 'light',
    colors: {
      text: '#2a180d',
      background: '#fffaf4',
      tint: orange,
      icon: '#826b5d',
      tabIconDefault: '#826b5d',
      tabIconSelected: orange,
      surface: '#ffffff',
      surfaceRaised: '#fff4e8',
      border: '#f2d9c4',
      subtleBackground: '#fff1e3',
      subtleBorder: '#ffd2a8',
      onTint: '#2a180d',
    },
  },
  yellow: {
    id: 'yellow',
    name: 'Yellow notebook',
    description: 'Bright yellow canvas with ink-blue accents.',
    colorScheme: 'light',
    colors: {
      text: '#29230a',
      background: '#fff3a6',
      tint: '#2543a5',
      icon: '#766c34',
      tabIconDefault: '#766c34',
      tabIconSelected: '#2543a5',
      surface: '#fffbe0',
      surfaceRaised: '#fff8bf',
      border: '#ded076',
      subtleBackground: '#fff8c8',
      subtleBorder: '#d8c763',
      onTint: '#ffffff',
    },
  },
  lavender: {
    id: 'lavender',
    name: 'Lavender',
    description: 'A calm, bright violet workspace.',
    colorScheme: 'light',
    colors: {
      text: '#261d3a',
      background: '#f7f1ff',
      tint: '#7451bd',
      icon: '#786d91',
      tabIconDefault: '#786d91',
      tabIconSelected: '#7451bd',
      surface: '#ffffff',
      surfaceRaised: '#f0e8ff',
      border: '#d9cbed',
      subtleBackground: '#eee4ff',
      subtleBorder: '#cdb8ec',
      onTint: '#ffffff',
    },
  },
  'sea-glass': {
    id: 'sea-glass',
    name: 'Sea glass',
    description: 'Cool blue paper with crisp ocean accents.',
    colorScheme: 'light',
    colors: {
      text: '#073b4c',
      background: '#eaf8ff',
      tint: '#0077b6',
      icon: '#568096',
      tabIconDefault: '#568096',
      tabIconSelected: '#0077b6',
      surface: '#ffffff',
      surfaceRaised: '#dcf4ff',
      border: '#b9dfef',
      subtleBackground: '#dff5ff',
      subtleBorder: '#a9d8ee',
      onTint: '#ffffff',
    },
  },
  'rose-paper': {
    id: 'rose-paper',
    name: 'Rose paper',
    description: 'Soft rose surfaces and confident berry controls.',
    colorScheme: 'light',
    colors: {
      text: '#3d1323',
      background: '#fff4f6',
      tint: '#bd3d69',
      icon: '#8b6070',
      tabIconDefault: '#8b6070',
      tabIconSelected: '#bd3d69',
      surface: '#ffffff',
      surfaceRaised: '#ffe8ee',
      border: '#efc9d6',
      subtleBackground: '#ffebf1',
      subtleBorder: '#eeb7c9',
      onTint: '#ffffff',
    },
  },
  alpine: {
    id: 'alpine',
    name: 'Alpine',
    description: 'Fresh mountain air with evergreen actions.',
    colorScheme: 'light',
    colors: {
      text: '#12372a',
      background: '#f2fbf7',
      tint: '#147a55',
      icon: '#62877a',
      tabIconDefault: '#62877a',
      tabIconSelected: '#147a55',
      surface: '#ffffff',
      surfaceRaised: '#e4f7ee',
      border: '#c5e5d6',
      subtleBackground: '#e9f8f0',
      subtleBorder: '#b4dcc9',
      onTint: '#ffffff',
    },
  },
  porcelain: {
    id: 'porcelain',
    name: 'Porcelain',
    description: 'A clean cool canvas with classic blue controls.',
    colorScheme: 'light',
    colors: {
      text: '#1d2940',
      background: '#f7f8fb',
      tint: '#3b5ccc',
      icon: '#68758c',
      tabIconDefault: '#68758c',
      tabIconSelected: '#3b5ccc',
      surface: '#ffffff',
      surfaceRaised: '#edf0f8',
      border: '#d4d9e8',
      subtleBackground: '#eef1f9',
      subtleBorder: '#c6cee3',
      onTint: '#ffffff',
    },
  },
  apricot: {
    id: 'apricot',
    name: 'Apricot',
    description: 'Sunlit fruit tones for an optimistic workspace.',
    colorScheme: 'light',
    colors: {
      text: '#3b1d0c',
      background: '#fff2e8',
      tint: '#d75b21',
      icon: '#99694e',
      tabIconDefault: '#99694e',
      tabIconSelected: '#d75b21',
      surface: '#ffffff',
      surfaceRaised: '#ffe2cf',
      border: '#f0c6aa',
      subtleBackground: '#ffeadc',
      subtleBorder: '#ebb894',
      onTint: '#241005',
    },
  },
  sakura: {
    id: 'sakura',
    name: 'Sakura',
    description: 'Petal pink with a precise magenta accent.',
    colorScheme: 'light',
    colors: {
      text: '#42132a',
      background: '#fff5fa',
      tint: '#d94078',
      icon: '#926275',
      tabIconDefault: '#926275',
      tabIconSelected: '#d94078',
      surface: '#ffffff',
      surfaceRaised: '#ffe8f2',
      border: '#efc9dc',
      subtleBackground: '#ffebf4',
      subtleBorder: '#eeb9d1',
      onTint: '#220410',
    },
  },
  moss: {
    id: 'moss',
    name: 'Moss',
    description: 'Quiet botanical greens and parchment surfaces.',
    colorScheme: 'light',
    colors: {
      text: '#293313',
      background: '#f4f8e9',
      tint: '#5c7f27',
      icon: '#78835c',
      tabIconDefault: '#78835c',
      tabIconSelected: '#5c7f27',
      surface: '#ffffff',
      surfaceRaised: '#e8f0d5',
      border: '#ceddaf',
      subtleBackground: '#ebf3d9',
      subtleBorder: '#c2d59e',
      onTint: '#ffffff',
    },
  },
  blueprint: {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Technical blue ink on a bright drafting surface.',
    colorScheme: 'light',
    colors: {
      text: '#152f52',
      background: '#eef5ff',
      tint: '#2563a8',
      icon: '#647d9b',
      tabIconDefault: '#647d9b',
      tabIconSelected: '#2563a8',
      surface: '#ffffff',
      surfaceRaised: '#dfecfc',
      border: '#bdd3ee',
      subtleBackground: '#e4f0ff',
      subtleBorder: '#aac8e9',
      onTint: '#ffffff',
    },
  },
  sand: {
    id: 'sand',
    name: 'Sand',
    description: 'Warm neutral paper with ochre navigation.',
    colorScheme: 'light',
    colors: {
      text: '#382b14',
      background: '#fff8e9',
      tint: '#9a6313',
      icon: '#85744e',
      tabIconDefault: '#85744e',
      tabIconSelected: '#9a6313',
      surface: '#ffffff',
      surfaceRaised: '#fff0cf',
      border: '#ead3a4',
      subtleBackground: '#fff3d9',
      subtleBorder: '#e3c68f',
      onTint: '#ffffff',
    },
  },
  cloud: {
    id: 'cloud',
    name: 'Cloud',
    description: 'Soft gray-blue focus without visual noise.',
    colorScheme: 'light',
    colors: {
      text: '#263442',
      background: '#f3f5f9',
      tint: '#425466',
      icon: '#70808f',
      tabIconDefault: '#70808f',
      tabIconSelected: '#425466',
      surface: '#ffffff',
      surfaceRaised: '#e9edf3',
      border: '#cfd8e2',
      subtleBackground: '#ebeff5',
      subtleBorder: '#c2cedb',
      onTint: '#ffffff',
    },
  },
  lilac: {
    id: 'lilac',
    name: 'Lilac',
    description: 'Pale violet paper with lively purple controls.',
    colorScheme: 'light',
    colors: {
      text: '#321a49',
      background: '#faf5ff',
      tint: '#8b50b4',
      icon: '#826d94',
      tabIconDefault: '#826d94',
      tabIconSelected: '#8b50b4',
      surface: '#ffffff',
      surfaceRaised: '#f2e7ff',
      border: '#dec9ef',
      subtleBackground: '#f4eaff',
      subtleBorder: '#d2b7eb',
      onTint: '#ffffff',
    },
  },
  glacier: {
    id: 'glacier',
    name: 'Glacier',
    description: 'Icy clarity with an anchored teal blue accent.',
    colorScheme: 'light',
    colors: {
      text: '#123946',
      background: '#eefaff',
      tint: '#0b7c9e',
      icon: '#5e8693',
      tabIconDefault: '#5e8693',
      tabIconSelected: '#0b7c9e',
      surface: '#ffffff',
      surfaceRaised: '#ddf4fb',
      border: '#b9e0eb',
      subtleBackground: '#e2f6fc',
      subtleBorder: '#a8d6e4',
      onTint: '#ffffff',
    },
  },
  midnight: {
    id: 'midnight',
    name: 'Midnight',
    description: 'Low-glare graphite with orange highlights.',
    colorScheme: 'dark',
    colors: {
      text: '#f5f0eb',
      background: '#16181d',
      tint: '#ff9c42',
      icon: '#aaaeb8',
      tabIconDefault: '#aaaeb8',
      tabIconSelected: '#ff9c42',
      surface: '#20232a',
      surfaceRaised: '#292d35',
      border: '#363b45',
      subtleBackground: '#2a211b',
      subtleBorder: '#5c412b',
      onTint: '#211100',
    },
  },
  forest: {
    id: 'forest',
    name: 'Night forest',
    description: 'Deep green surfaces with fresh mint accents.',
    colorScheme: 'dark',
    colors: {
      text: '#edf7ef',
      background: '#10221c',
      tint: '#77d6a5',
      icon: '#9db6aa',
      tabIconDefault: '#9db6aa',
      tabIconSelected: '#77d6a5',
      surface: '#173129',
      surfaceRaised: '#1e3d33',
      border: '#315348',
      subtleBackground: '#1b3b30',
      subtleBorder: '#356451',
      onTint: '#092117',
    },
  },
  'indigo-dusk': {
    id: 'indigo-dusk',
    name: 'Indigo dusk',
    description: 'Blue-violet night with luminous periwinkle accents.',
    colorScheme: 'dark',
    colors: {
      text: '#f1f0ff',
      background: '#17182f',
      tint: '#aaa7ff',
      icon: '#afb0d0',
      tabIconDefault: '#afb0d0',
      tabIconSelected: '#aaa7ff',
      surface: '#222342',
      surfaceRaised: '#2b2d50',
      border: '#3c3e68',
      subtleBackground: '#27284b',
      subtleBorder: '#4b4d82',
      onTint: '#17172e',
    },
  },
  ember: {
    id: 'ember',
    name: 'Ember',
    description: 'Charcoal warmth with glowing coral actions.',
    colorScheme: 'dark',
    colors: {
      text: '#fff2ed',
      background: '#251713',
      tint: '#ff765a',
      icon: '#c9aaa2',
      tabIconDefault: '#c9aaa2',
      tabIconSelected: '#ff9279',
      surface: '#35201a',
      surfaceRaised: '#442720',
      border: '#5d3a31',
      subtleBackground: '#3a211b',
      subtleBorder: '#704236',
      onTint: '#35130c',
    },
  },
  'deep-ocean': {
    id: 'deep-ocean',
    name: 'Deep ocean',
    description: 'Inky blue depth with clear cyan navigation.',
    colorScheme: 'dark',
    colors: {
      text: '#e8f7ff',
      background: '#081e2d',
      tint: '#4dc9f6',
      icon: '#9cbccb',
      tabIconDefault: '#9cbccb',
      tabIconSelected: '#71d7fa',
      surface: '#102c3d',
      surfaceRaised: '#17394d',
      border: '#2d5267',
      subtleBackground: '#123547',
      subtleBorder: '#376c84',
      onTint: '#06212d',
    },
  },
  obsidian: {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Near-black calm with a refined golden accent.',
    colorScheme: 'dark',
    colors: {
      text: '#f4f2ed',
      background: '#121316',
      tint: '#e3b341',
      icon: '#b7b4aa',
      tabIconDefault: '#b7b4aa',
      tabIconSelected: '#f0c95c',
      surface: '#1c1d21',
      surfaceRaised: '#27272c',
      border: '#39393d',
      subtleBackground: '#282317',
      subtleBorder: '#5d4b27',
      onTint: '#211705',
    },
  },
  plum: {
    id: 'plum',
    name: 'Plum',
    description: 'Velvety purple night with electric orchid actions.',
    colorScheme: 'dark',
    colors: {
      text: '#faefff',
      background: '#26152f',
      tint: '#e699ff',
      icon: '#c4a6ca',
      tabIconDefault: '#c4a6ca',
      tabIconSelected: '#efb0ff',
      surface: '#382040',
      surfaceRaised: '#482950',
      border: '#66426d',
      subtleBackground: '#402345',
      subtleBorder: '#7c4e86',
      onTint: '#301039',
    },
  },
  aurora: {
    id: 'aurora',
    name: 'Aurora',
    description: 'Deep teal night illuminated by mint light.',
    colorScheme: 'dark',
    colors: {
      text: '#e8fffa',
      background: '#0e2429',
      tint: '#62e1c7',
      icon: '#9fc9bf',
      tabIconDefault: '#9fc9bf',
      tabIconSelected: '#7eedda',
      surface: '#17363a',
      surfaceRaised: '#1e474a',
      border: '#356568',
      subtleBackground: '#193d3d',
      subtleBorder: '#417978',
      onTint: '#082b27',
    },
  },
  cobalt: {
    id: 'cobalt',
    name: 'Cobalt',
    description: 'A composed navy workspace with bright blue focus.',
    colorScheme: 'dark',
    colors: {
      text: '#edf3ff',
      background: '#111d3d',
      tint: '#75a7ff',
      icon: '#a5b8df',
      tabIconDefault: '#a5b8df',
      tabIconSelected: '#91bbff',
      surface: '#1b2c54',
      surfaceRaised: '#243866',
      border: '#415887',
      subtleBackground: '#20315b',
      subtleBorder: '#5671a7',
      onTint: '#102453',
    },
  },
  espresso: {
    id: 'espresso',
    name: 'Espresso',
    description: 'Rich coffee surfaces with warm caramel controls.',
    colorScheme: 'dark',
    colors: {
      text: '#fff4eb',
      background: '#211815',
      tint: '#e5a567',
      icon: '#c6ab98',
      tabIconDefault: '#c6ab98',
      tabIconSelected: '#f1ba83',
      surface: '#32241f',
      surfaceRaised: '#422f28',
      border: '#60473b',
      subtleBackground: '#38251e',
      subtleBorder: '#745341',
      onTint: '#2c190b',
    },
  },
  slate: {
    id: 'slate',
    name: 'Slate',
    description: 'Cool slate surfaces and clear sky-blue guidance.',
    colorScheme: 'dark',
    colors: {
      text: '#edf7fc',
      background: '#18212a',
      tint: '#8bc5e8',
      icon: '#aec4d0',
      tabIconDefault: '#aec4d0',
      tabIconSelected: '#a6d8f4',
      surface: '#24313c',
      surfaceRaised: '#2d3d49',
      border: '#465b69',
      subtleBackground: '#293a45',
      subtleBorder: '#597687',
      onTint: '#102b3b',
    },
  },
  ruby: {
    id: 'ruby',
    name: 'Ruby',
    description: 'Deep garnet with bright rose-red actions.',
    colorScheme: 'dark',
    colors: {
      text: '#fff0f3',
      background: '#2a131a',
      tint: '#ff718a',
      icon: '#d1a2ad',
      tabIconDefault: '#d1a2ad',
      tabIconSelected: '#ff91a5',
      surface: '#3b1d27',
      surfaceRaised: '#4c2633',
      border: '#703a4b',
      subtleBackground: '#44202d',
      subtleBorder: '#86445a',
      onTint: '#3e0d18',
    },
  },
  jade: {
    id: 'jade',
    name: 'Jade',
    description: 'Dark mineral green energized by lime highlights.',
    colorScheme: 'dark',
    colors: {
      text: '#f1ffe6',
      background: '#0f251e',
      tint: '#a7e36a',
      icon: '#b1cba3',
      tabIconDefault: '#b1cba3',
      tabIconSelected: '#bee987',
      surface: '#19372c',
      surfaceRaised: '#224836',
      border: '#3a674e',
      subtleBackground: '#1d3e2d',
      subtleBorder: '#4c7c57',
      onTint: '#18300b',
    },
  },
  solarized: {
    id: 'solarized',
    name: 'Solarized',
    description: 'Classic blue-green contrast for long focused sessions.',
    colorScheme: 'dark',
    colors: {
      text: '#e2f0ee',
      background: '#002b36',
      tint: '#2aa198',
      icon: '#9bbfba',
      tabIconDefault: '#9bbfba',
      tabIconSelected: '#49c2b9',
      surface: '#073b46',
      surfaceRaised: '#0d4b55',
      border: '#27636a',
      subtleBackground: '#0a444b',
      subtleBorder: '#36777a',
      onTint: '#002d29',
    },
  },
  monochrome: {
    id: 'monochrome',
    name: 'Monochrome',
    description: 'Neutral graphite with clean white emphasis.',
    colorScheme: 'dark',
    colors: {
      text: '#f4f4f4',
      background: '#202020',
      tint: '#d8d8d8',
      icon: '#b2b2b2',
      tabIconDefault: '#b2b2b2',
      tabIconSelected: '#ffffff',
      surface: '#2b2b2b',
      surfaceRaised: '#373737',
      border: '#4b4b4b',
      subtleBackground: '#313131',
      subtleBorder: '#606060',
      onTint: '#1d1d1d',
    },
  },
};

export const DEFAULT_THEME_ID: AppThemeId = 'system';

export function resolveAppTheme(
  themeId: AppThemeId,
  systemColorScheme: ColorScheme,
): AppTheme {
  return themeId === 'system'
    ? APP_THEMES[systemColorScheme === 'dark' ? 'midnight' : 'sunrise']
    : APP_THEMES[themeId];
}
