from collections import Counter


TOPICS_RAW = [
    # general / trends
    "nocode",
    "lowcode",
    "modern",
    "web3",
    "blockchain",
    "crypto",
    "startup",
    "saas",
    "productivity",
    "automation",

    # mobile / apps
    "mobile",
    "mobile-first",
    "offline-first",
    "react-native",
    "ionic",
    "flutter",
    "expo",
    "android",
    "ios",
    "pwa",
    "progressive-web-app",
    "isomorphic",
    "webassembly",

    "wasm",
    "desktop",
    "ssr",
    "operating-systems",
    "software-development",
    "user-interface",
    "react",
    "css",
    "html", 
    "rust",
    "golang",
    "go",
    "php",
    "csharp",
    "c#",
    "c++",
    "cplusplus",
    "native", 
    "virtualdom"

    # content / personal tools
    "journal",
    "notes",
    "knowledge-base",
    "wiki",
    "cms",
    "headless-cms",

    # architecture / paradigms
    "declarative",
    "imperative",
    "functional",
    "functional-programming",
    "oop",
    "reactive",
    "event-driven",
    "fullstack",
    "monolith",
    "modular",
    "clean-architecture",
    "hexagonal-architecture",
    "ddd",
    "cqrs",

    # languages
    "rust",
    "kotlin",
    "javascript",
    "typescript",
    "python",
    "go",
    "java",
    "csharp",
    "swift",
    "dart",

    # cross-platform
    "crossplatform",
    "cross-platform",
    "multiplatform",

    # UI / components
    "ui",
    "ux",
    "ui-components",
    "component-library",
    "design-system",
    "storybook",
    "tailwind",
    "material-ui",
    "chakra-ui",
    "shadcn",

    # tables / data UI
    "table",
    "datatable",
    "grid",
    "treetable",
    "tree-table",

    # frontend ecosystem
    "frontend",
    "web",
    "html",
    "css",
    "responsive-design",
    "accessibility",
    "a11y",
    "react",
    "vue",
    "angular",
    "svelte",
    "solidjs",
    "nextjs",
    "nuxt",
    "remix",
    "vite",
    "webpack",
    "babel",

    # backend ecosystem
    "backend",
    "api",
    "rest",
    "graphql",
    "grpc",
    "microservices",
    "server",
    "serverless",
    "edge-functions",
    "nodejs",
    "fastapi",
    "django",
    "flask",
    "express",
    "nestjs",
    "auth",
    "authentication",
    "authorization",
    "oauth",
    "jwt",

    # databases / data layer
    "db",
    "database",
    "sql",
    "nosql",
    "orm",
    "prisma",
    "drizzle",
    "postgres",
    "mysql",
    "sqlite",
    "mongodb",
    "redis",
    "elasticsearch",
    "vector-database",
    "supabase",
    "firebase",

    # AI / ML / LLM ecosystem
    "ai",
    "ml",
    "machine-learning",
    "deep-learning",
    "llm",
    "large-language-model",
    "generative-ai",
    "ai-agents",
    "autonomous-agents",
    "transformer",
    "embeddings",
    "rag",
    "fine-tuning",
    "prompt-engineering",
    "langchain",
    "langgraph",
    "llamaindex",
    "huggingface",
    "pytorch",
    "tensorflow",
    "openai-api",
    "multimodal",
    "speech-to-text",
    "text-to-speech",
    "computer-vision",

    # smart home / iot
    "smart-home",
    "iot",
    "home-automation",
    "domotics",
    "edge-computing",
    "edge-ai",
    "embedded",
    "firmware",
    "raspberry-pi",
    "arduino",
    "esp32",
    "esp8266",
    "zigbee",
    "zwave",
    "mqtt",
    "matter",
    "thread-protocol",
    "home-assistant",
    "openhab",
    "smartthings",
    "homekit",
    "alexa",
    "google-home",
    "sensor",
    "actuator",
    "automation-rules",
    "energy-monitoring",
    "smart-lighting",
    "smart-security",

    # dev tools / infra
    "devops",
    "docker",
    "kubernetes",
    "ci-cd",
    "github-actions",
    "cloud",
    "aws",
    "gcp",
    "azure",
    "vercel",
    "netlify",
    "infrastructure",
    "terraform",
    "ansible",
    "observability",
    "monitoring",
    "logging",

    # engineering quality
    "testing",
    "unit-testing",
    "integration-testing",
    "e2e-testing",
    "playwright",
    "cypress",
    "performance",
    "optimization",
    "security",
    "tdd",
    "linting",
    "formatting",

    # repo types / discovery
    "boilerplate",
    "starter-template",
    "template",
    "example",
    "tutorial",
    "guide",
    "awesome-list",
    "scaffold",
]

# --- Duplicate detection ---
counts = Counter(TOPICS_RAW)
duplicates = [item for item, count in counts.items() if count > 1]

if duplicates:
    print("⚠️ Duplicate topics detected:", duplicates)

# --- Deduplication while preserving order ---
TOPICS = list(dict.fromkeys(TOPICS_RAW))# --- Duplicate detection ---
counts = Counter(TOPICS_RAW)
duplicates = [item for item, count in counts.items() if count > 1]

if duplicates:
    print("⚠️ Duplicate topics detected:", duplicates)

# --- Deduplication while preserving order ---
TOPICS = list(dict.fromkeys(TOPICS_RAW))

