from collections import Counter

# --- Deduplication while preserving order ---
# Explicit repos to include in every fetch run, independent of topic search results.
# Accepts full GitHub URLs or owner/repo identifiers.
HARDCODED_REPOS_RAW = [
    "https://github.com/anomalyco/opencode",
    "https://github.com/googleapis/js-genai",
    "https://github.com/Wei-Shaw/sub2api",
    "https://github.com/AmazingAng/auth2api",
    "https://github.com/kittors/CliRelay",
    "https://github.com/router-for-me/CLIProxyAPI",
    "https://github.com/AlexAnys/ai-sub-auth",
    "https://github.com/andrewyng/aisuite",
    "https://github.com/bitovi/react-to-web-component",
    "https://github.com/webcomponents/polyfills",
    "https://github.com/salesforce/lwc",

    # MCP SDKs
    "https://github.com/modelcontextprotocol/typescript-sdk",
    "https://github.com/modelcontextprotocol/csharp-sdk",
    "https://github.com/modelcontextprotocol/rust-sdk",
    "https://github.com/modelcontextprotocol/python-sdk",
    "https://github.com/modelcontextprotocol/go-sdk",
    "https://github.com/modelcontextprotocol/java-sdk",
    "https://github.com/modelcontextprotocol/php-sdk",
    "https://github.com/modelcontextprotocol/swift-sdk",

    "https://github.com/MadsLorentzen/ai-job-search",
    
]

TOPICS_RAW = [
    # general / trends
    "baas",
    "nocode",
    "lowcode",
    "low-code",
    "low-code-platform", # budibase

    *"blog documentation wiki project-management content-management note-taking flutter task-management content-services team-collaboration notion-alternative confluence-alternative".split(" "),
    *"electron editor markdown rust app wiki notes table rust-language workspace whiteboard tableview rust-lang crdt knowledge-base notion miro notion-alternative".split(" "),
    *"react javascript typescript chatbot artificial-intelligence openai multiagent-systems agents workflow-automation low-code no-code rag large-language-models chatgpt langchain agentic-workflow agentic-ai".split(" "),
    *"react nodejs javascript ecommerce framework typescript commerce medusa e-commerce".split(" "),
    *"language programming-language compiler v".split(" "),
    *"react agent open-source typescript ai js reactjs nextjs ts assistant copilot agents assistant-chat-bots ai-assistant ai-agent llm copilot-chat generative-ui agentic-ai agent-native".split(" "),
    *"reinforcement-learning transformers pytorch diffusion dit video-generation world-models sana text-to-video linear-transformer text-to-image-generation system-algorithm-deisgn ystem-algorithm-design nvfp4".split(" "),
    *"ui ai mcp openapi self-hosted openai webui rag llm llms ollama llm-ui ollama-webui llm-webui open-webui".split(" "),
    *"sql database web serverless nosql devtools distributed database-as-a-service developer-tools graph-database distributed-database document-database realtime-database backend-as-a-service cloud-database surreal surrealdb iot-database".split(" "),
    *"search search-engine machine-learning neural-network nearest-neighbor-search image-search recommender-system search-engines similarity-search ai-search knn-algorithm mlops hnsw vector-search vector-database neural-search vector-search-engine embeddings-similarity hybrid-search ai-search-engine".split(" "),
    "mobx",
    "redux",
    "zustand",
    "state-management",

    "no-code-platform",
    "low-code-no-code",
    "airtable",
    "airtable-replacement",
    "airtable-alternative",
    "spreadsheet",
    "self-hosted",
    "budibase",
    "langchain",

    "modern",
    "web3",
    "blockchain",
    "crypto",
    "startup",
    "saas",
    "productivity",
    "automation",
    "assistant",
    "personal-assistant",
    "devin",
    "awesome",
    "awesome-list",
    "mcp",
    "gpt",
    "chat",
    "chatbot",
    "chatgpt",

    # mobile / apps
    "mobile",
    "mobile-first",
    "offline-first",
    "react-native",

    "ionic",
    "capacitor",
    "stencil",

    "flutter",
    "expo",
    "android",
    "ios",
    "pwa",
    "progressive-web-app",
    "isomorphic",
    "webassembly",

    "wasm",
    "desktop",
    "ssr",
    "operating-systems",
    "software-development",
    "user-interface",
    "react",
    "css",
    "html", 
    "rust",
    "golang",
    "go",
    "php",
    "csharp",
    "c#",
    "c++",
    "cplusplus",
    "native", 
    "virtualdom",

    # content / personal tools
    "journal",
    "notes",
    "knowledge-base",
    "wiki",
    "cms",
    "headless-cms",

    # architecture / paradigms
    "declarative",
    "imperative",
    "functional",
    "functional-programming",
    "oop",
    "reactive",
    "event-driven",
    "fullstack",
    "monolith",
    "modular",
    "clean-architecture",
    "hexagonal-architecture",
    "ddd",
    "cqrs",

    # languages
    "rust",
    "kotlin",
    "javascript",
    "typescript",
    "python",
    "go",
    "java",
    "csharp",
    "swift",
    "dart",

    # cross-platform
    "crossplatform",
    "cross-platform",
    "multiplatform",

    # UI / components
    "ui",
    "ux",
    "ui-components",
    "component-library",
    "framework",
    "ui-framework",
    "framework-agnostic",
    "design-system",
    "storybook",
    "tailwind",
    "material-ui",
    "chakra-ui",
    "shadcn",
    "web-components", "webcomponents",
    "web-component", "webcomponent",
    "lwc",

    # tables / data UI
    "table",
    "datatable",
    "data-table",
    "grid",
    "treetable",
    "tree-table",

    # frontend ecosystem
    "frontend",
    "web",
    "html",
    "css",
    "responsive-design",
    "accessibility",
    "a11y",
    "react",
    "vue",
    "angular",
    "svelte",
    "solidjs",
    "nextjs",
    "nuxt",
    "remix",
    "vite",
    "webpack",
    "babel",

    # backend ecosystem
    "backend",
    "api",
    "rest",
    "graphql",
    "grpc",
    "microservices",
    "server",
    "serverless",
    "edge-functions",
    "nodejs",
    "fastapi",
    "django",
    "flask",
    "express",
    "nestjs",
    "auth",
    "authentication",
    "authorization",
    "oauth",
    "jwt",

    # databases / data layer
    "db",
    "database",
    "sql",
    "nosql",
    "orm",
    "prisma",
    "drizzle",
    "postgres",
    "postgresql",
    "mysql",
    "sqlite",
    "mongodb",
    "redis",
    "elasticsearch",
    "vector-database",
    "supabase",
    "firebase",
    "firebase-replacement",
    "firebase-alternative",
    "firestore",
    "firestore-replacement",
    "firestore-alternative",

    # AI / ML / LLM ecosystem
    "ai",
    "ml",
    "machine-learning",
    "deep-learning",
    "llm",
    "large-language-model",
    "generative-ai",
    "ai-agents",
    "autonomous-agents",
    "agents",
    "transformer",
    "embeddings",
    "rag",
    "fine-tuning",
    "prompt-engineering",
    "langchain",
    "langgraph",
    "llamaindex",
    "huggingface",
    "pytorch",
    "tensorflow",
    "openai",
    "openai-api",
    "artificial-intelligence",
    "claude-ai",
    "multimodal",
    "speech-to-text",
    "text-to-speech",
    "computer-vision",
    "autogen",
    "agent-framework",
    "agentic-ai",
    "a2a",
    "a2a-protocol",



    "developer-tools",
    "coderabbit",
    "coderabbitai",

    # smart home / iot
    "smart-home",
    "iot",
    "home-automation",
    "domotics",
    "edge-computing",
    "edge-ai",
    "embedded",
    "firmware",
    "raspberry-pi",
    "arduino",
    "esp32",
    "esp8266",
    "zigbee",
    "zwave",
    "mqtt",
    "matter",
    "thread-protocol",
    "home-assistant",
    "openhab",
    "smartthings",
    "homekit",
    "alexa",
    "google-home",
    "sensor",
    "actuator",
    "automation-rules",
    "energy-monitoring",
    "smart-lighting",
    "smart-security",

    # dev tools / infra
    "devops",
    "docker",
    "kubernetes",
    "ci-cd",
    "github-actions",
    "cloud",
    "aws",
    "gcp",
    "azure",
    "vercel",
    "netlify",
    "infrastructure",
    "terraform",
    "ansible",
    "observability",
    "monitoring",
    "logging",

    # engineering quality
    "testing",
    "unit-testing",
    "integration-testing",
    "e2e-testing",
    "playwright",
    "cypress",
    "performance",
    "optimization",
    "security",
    "tdd",
    "linting",
    "formatting",

    # repo types / discovery
    "boilerplate",
    "starter-template",
    "template",
    "example",
    "tutorial",
    "guide",
    "awesome-list",
    "scaffold",
]

# --- Duplicate detection ---
counts = Counter(TOPICS_RAW)
duplicates = [item for item, count in counts.items() if count > 1]

if duplicates:
    print(f"⚠️ {len(duplicates)} duplicate topic(s) detected:", duplicates)

TOPICS = list(dict.fromkeys(TOPICS_RAW))



HARDCODED_REPOS = list(dict.fromkeys(HARDCODED_REPOS_RAW))

