// Thin TypeScript wrapper around the Rust/WASM SyncClient.
//
// Exposes:
//   - `events$`      — Observable<ServerEvent> from the gRPC Subscribe stream
//   - `queueLength$` — BehaviorSubject<number> that tracks pending upload count
//   - Mutation methods matching the tableApi.ts interface (for easy migration)
//
// The WASM module is loaded lazily on first call to `getSyncClient()`.
// Once loaded it is a singleton; safe to call from multiple components.

import { BehaviorSubject, Observable, Subject } from 'rxjs';
import { share, takeUntil } from 'rxjs/operators';

// ── Proto-aligned event types (mirrors structable.proto ServerEvent) ──────────

export type FlagData      = { id: string; key: string; color: string };
export type RemarkTarget  = { row_id: string; column_id: string };
export type RemarkData    = { id: string; body: string; kind: 'note'|'comment'; is_private: boolean; resolved_at: string; targets: RemarkTarget[] };
export type HiddenRowData = { id: string; row_id: string };
export type HiddenColData = { id: string; column_id: string };
export type CustomColData = { id: string; name: string; label: string; expression: string; position_after: string; read_only: boolean; readOnly: boolean; types: string[] };

export type EventKind = 0 | 1; // 0=UPSERT, 1=DELETE

export type ServerEvent =
  | { ack:        { op_id: string; response: Uint8Array } }
  | { error:      { op_id: string; message: string } }
  | { flag:       { kind: EventKind; data: FlagData } }
  | { remark:     { kind: EventKind; data: RemarkData } }
  | { hidden_row: { kind: EventKind; data: HiddenRowData } }
  | { hidden_col: { kind: EventKind; data: HiddenColData } }
  | { custom_col: { kind: EventKind; data: CustomColData } };

// ── WASM module type (generated by wasm-pack) ──────────────────────────────────

interface WasmSyncClient {
  new (baseUrl: string): WasmSyncClient;
  init(): Promise<void>;
  set_on_queue_change(cb: (count: number) => void): void;
  set_on_error(cb: (msg: string) => void): void;
  subscribe(onEvent: (json: string) => void): () => void;
  queue_length(): number;

  upsert_flag(key: string, color: string): Promise<void>;
  delete_flag(key: string): Promise<void>;
  upsert_remark(existingId: string | null, kind: string, body: string, targetsJson: string): Promise<string>;
  delete_remark(id: string): Promise<void>;
  add_hidden_row(repoId: number): Promise<void>;
  remove_hidden_row(repoId: number): Promise<void>;
  add_hidden_column(columnId: string): Promise<void>;
  remove_hidden_column(columnId: string): Promise<void>;
  create_custom_column(payloadJson: string): Promise<string>;
  delete_custom_column(id: string): Promise<void>;

  fetch_flags(): Promise<string>;
  fetch_remarks(): Promise<string>;
  fetch_hidden_rows(): Promise<string>;
  fetch_hidden_columns(): Promise<string>;
  fetch_custom_columns(): Promise<string>;
  fetch_repos(paramsJson: string): Promise<string>;
}

interface WasmModule {
  SyncClient: new (baseUrl: string) => WasmSyncClient;
}

// ── Singleton plumbing ─────────────────────────────────────────────────────────

const GRPC_BASE = process.env.NEXT_PUBLIC_GRPC_URL ?? 'http://localhost:3002';

let _wasm: WasmModule | null = null;
let _client: WasmSyncClient | null = null;
let _initPromise: Promise<SyncClient> | null = null;

async function loadWasm(): Promise<WasmModule> {
  if (_wasm) return _wasm;
  // wasm-pack --target web outputs sync_core.js + sync_core_bg.wasm into public/wasm/
  // Next.js serves public/ as static assets.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const mod = await import(/* webpackIgnore: true */ '/wasm/sync_core.js' as any);
  // --target web requires calling the default init() to fetch + instantiate the .wasm binary.
  // Without args it resolves sync_core_bg.wasm relative to the JS file URL.
  await mod.default();
  _wasm = mod as WasmModule;
  return _wasm;
}

// ── SyncClient wrapper ─────────────────────────────────────────────────────────

export class SyncClient {
  readonly events$:      Observable<ServerEvent>;
  readonly queueLength$: BehaviorSubject<number>;

  private inner:   WasmSyncClient;
  private destroy$ = new Subject<void>();

  private constructor(inner: WasmSyncClient, events$: Observable<ServerEvent>, queueLength$: BehaviorSubject<number>) {
    this.inner       = inner;
    this.events$     = events$;
    this.queueLength$ = queueLength$;
  }

  static async create(): Promise<SyncClient> {
    const wasm = await loadWasm();
    const inner = new wasm.SyncClient(GRPC_BASE);
    const queueLength$ = new BehaviorSubject<number>(inner.queue_length());

    inner.set_on_queue_change((count) => queueLength$.next(count));
    inner.set_on_error((msg) => console.error('[sync_core]', msg));

    // Build a cold Observable that starts the gRPC Subscribe stream
    const rawEvents$ = new Observable<ServerEvent>((subscriber) => {
      const unsub = inner.subscribe((json: string) => {
        subscriber.next(JSON.parse(json) as ServerEvent);
      });
      return () => {
        unsub?.();
        subscriber.complete();
      };
    });

    // share() so multiple consumers reuse one gRPC stream
    const events$ = rawEvents$.pipe(share());

    const client = new SyncClient(inner, events$, queueLength$);
    await inner.init();
    return client;
  }

  destroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  get queueLength(): number {
    return this.inner.queue_length();
  }

  // ── Mutations ────────────────────────────────────────────────────────────────

  upsertFlag(key: string, color: string):         Promise<void>   { return this.inner.upsert_flag(key, color); }
  deleteFlag(key: string):                         Promise<void>   { return this.inner.delete_flag(key); }

  upsertRemark(
    id: string | null,
    kind: 'note' | 'comment',
    body: string,
    targets: RemarkTarget[],
  ): Promise<string> {
    // WASM/gRPC wire still uses {repo_id: number}; convert at boundary.
    // TODO: update sync_core Rust to accept {row_id: string} natively.
    const wire = targets.map((t) => ({ repo_id: t.row_id === '' ? 0 : parseInt(t.row_id, 10), column_id: t.column_id }));
    return this.inner.upsert_remark(id, kind, body, JSON.stringify(wire));
  }

  deleteRemark(id: string):          Promise<void> { return this.inner.delete_remark(id); }
  // TODO: update sync_core to accept string rowId natively.
  addHiddenRow(rowId: string):       Promise<void> { return this.inner.add_hidden_row(parseInt(rowId, 10)); }
  removeHiddenRow(rowId: string):    Promise<void> { return this.inner.remove_hidden_row(parseInt(rowId, 10)); }
  addHiddenColumn(columnId: string):                Promise<void>   { return this.inner.add_hidden_column(columnId); }
  removeHiddenColumn(columnId: string):             Promise<void>   { return this.inner.remove_hidden_column(columnId); }
  deleteCustomColumn(id: string):                   Promise<void>   { return this.inner.delete_custom_column(id); }

  createCustomColumn(payload: {
    name: string; label?: string | null; description?: string | null; expression?: string | null; position_after?: string | null;
  }, id?: string): Promise<string> {
    return this.inner.create_custom_column(JSON.stringify({ ...payload, id: id ?? null }));
  }

  // ── Reads ────────────────────────────────────────────────────────────────────

  async fetchFlags():         Promise<import('../types/table').ApiFlag[]>         { return JSON.parse(await this.inner.fetch_flags()); }
  async fetchRemarks():       Promise<import('../types/table').ApiRemark[]>       { return JSON.parse(await this.inner.fetch_remarks()); }
  async fetchHiddenRows():    Promise<import('../types/table').ApiHiddenRow[]>    { return JSON.parse(await this.inner.fetch_hidden_rows()); }
  async fetchHiddenColumns(): Promise<import('../types/table').ApiHiddenColumn[]> { return JSON.parse(await this.inner.fetch_hidden_columns()); }
  async fetchCustomColumns(): Promise<import('../types/table').ApiCustomColumn[]> { return JSON.parse(await this.inner.fetch_custom_columns()); }

  async fetchRepos(params: URLSearchParams, _signal?: AbortSignal): Promise<import('../types/table').PagedResponse> {
    const NUM_PARAMS = new Set(['page', 'per_page']);
    const obj: Record<string, string | number> = {};
    params.forEach((v, k) => { obj[k] = NUM_PARAMS.has(k) ? Number(v) : v; });
    return JSON.parse(await this.inner.fetch_repos(JSON.stringify(obj)));
  }
}

// ── Module-level singleton ─────────────────────────────────────────────────────

export function getSyncClient(): Promise<SyncClient> {
  if (!_initPromise) {
    _initPromise = SyncClient.create().catch((err) => {
      // Reset so a retry is possible after a transient failure
      _initPromise = null;
      throw err;
    });
  }
  return _initPromise;
}

// ── React hook ────────────────────────────────────────────────────────────────

export { Observable };
