/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/repos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Repos
         * @description Fetch all repositories
         */
        get: operations["get_repos_repos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Repo */
        Repo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Stars */
            stars: number;
            /** Pushed At */
            pushed_at: string;
            /** Description */
            description?: string | null;
            /** Language */
            language?: string | null;
            /**
             * Forks
             * @default 0
             */
            forks: number;
            /**
             * Open Issues
             * @default 0
             */
            open_issues: number;
            /**
             * Watchers
             * @default 0
             */
            watchers: number;
            /** Owner Login */
            owner_login?: string | null;
            /** Owner Avatar */
            owner_avatar?: string | null;
            /** Owner Url */
            owner_url?: string | null;
            /** Topics */
            topics?: string[];
            /** License */
            license?: string | null;
            /** Homepage */
            homepage?: string | null;
            /**
             * Default Branch
             * @default main
             */
            default_branch: string;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /** Created At */
            created_at?: string | null;
            /** Updated At */
            updated_at?: string | null;
            /** Size */
            size?: number | null;
            /** Visibility */
            visibility?: string | null;
            /**
             * Has Issues
             * @default true
             */
            has_issues: boolean;
            /**
             * Has Projects
             * @default true
             */
            has_projects: boolean;
            /**
             * Has Wiki
             * @default true
             */
            has_wiki: boolean;
            /**
             * Has Pages
             * @default false
             */
            has_pages: boolean;
            /**
             * Has Downloads
             * @default true
             */
            has_downloads: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_repos_repos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Repo"][];
                };
            };
        };
    };
}
