// sync_core — offline-first sync layer compiled to WebAssembly.
//
// Replaces the TypeScript TableApi class. Exposes SyncClient to JavaScript
// via wasm-bindgen. All mutations are queued in IndexedDB before being sent
// via gRPC-Web so they survive page reloads and network outages.

use std::cell::RefCell;
use std::rc::Rc;

use gloo_timers::future::TimeoutFuture;
use rexie::{Index, ObjectStore, Rexie, TransactionMode};
use serde::{Deserialize, Serialize};
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::future_to_promise;

// ── Proto generated code ───────────────────────────────────────────────────────

pub mod proto {
    // Generated by tonic-build from proto/structable.proto
    tonic::include_proto!("structable");
}

use proto::{
    client_op::Payload as OpPayload,
    sync_client::SyncClient as GrpcSyncClient,
    *,
};
use tonic_web_wasm_client::Client as WasmTransport;

// ── Queued operation (stored in IDB) ──────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
struct QueuedOp {
    op_id:   String,
    seq:     u64,
    retries: u32,
    // Discriminant matching ClientOp oneof payload field names
    kind:    String,
    // JSON-encoded payload for this specific op type
    data:    serde_json::Value,
}

impl QueuedOp {
    fn into_client_op(self) -> Option<ClientOp> {
        let payload = match self.kind.as_str() {
            "upsert_flag" => Some(OpPayload::UpsertFlag(UpsertFlagOp {
                key:   self.data["key"].as_str().unwrap_or("").to_string(),
                color: self.data["color"].as_str().unwrap_or("").to_string(),
            })),
            "delete_flag" => Some(OpPayload::DeleteFlag(DeleteFlagOp {
                key: self.data["key"].as_str().unwrap_or("").to_string(),
            })),
            "upsert_remark" => Some(OpPayload::UpsertRemark(UpsertRemarkOp {
                id:   self.data["id"].as_str().unwrap_or("").to_string(),
                body: self.data["body"].as_str().unwrap_or("").to_string(),
                kind: self.data["kind"].as_str().unwrap_or("note").to_string(),
                targets: self.data["targets"]
                    .as_array()
                    .map(|arr| arr.iter().filter_map(|t| {
                        Some(RemarkTarget {
                            repo_id:   t["repo_id"].as_i64().unwrap_or(0),
                            column_id: t["column_id"].as_str()?.to_string(),
                        })
                    }).collect())
                    .unwrap_or_default(),
            })),
            "delete_remark" => Some(OpPayload::DeleteRemark(DeleteRemarkOp {
                id: self.data["id"].as_str().unwrap_or("").to_string(),
            })),
            "add_hidden_row" => Some(OpPayload::AddHiddenRow(AddHiddenRowOp {
                repo_id: self.data["repo_id"].as_i64().unwrap_or(0),
            })),
            "remove_hidden_row" => Some(OpPayload::RemoveHiddenRow(RemoveHiddenRowOp {
                repo_id: self.data["repo_id"].as_i64().unwrap_or(0),
            })),
            "add_hidden_col" => Some(OpPayload::AddHiddenCol(AddHiddenColumnOp {
                column_id: self.data["column_id"].as_str().unwrap_or("").to_string(),
            })),
            "remove_hidden_col" => Some(OpPayload::RemoveHiddenCol(RemoveHiddenColumnOp {
                column_id: self.data["column_id"].as_str().unwrap_or("").to_string(),
            })),
            "create_custom_col" => Some(OpPayload::CreateCustomCol(CreateCustomColOp {
                id:             self.data["id"].as_str().unwrap_or("").to_string(),
                name:           self.data["name"].as_str().unwrap_or("").to_string(),
                label:          self.data["label"].as_str().unwrap_or("").to_string(),
                expression:     self.data["expression"].as_str().unwrap_or("").to_string(),
                position_after: self.data["position_after"].as_str().unwrap_or("").to_string(),
                description:    self.data["description"].as_str().unwrap_or("").to_string(),
            })),
            "delete_custom_col" => Some(OpPayload::DeleteCustomCol(DeleteCustomColOp {
                id: self.data["id"].as_str().unwrap_or("").to_string(),
            })),
            _ => None,
        }?;
        Some(ClientOp {
            op_id: self.op_id,
            seq:   self.seq,
            payload: Some(payload),
        })
    }
}

// ── Inner state ────────────────────────────────────────────────────────────────

struct Inner {
    base_url:        String,
    queue:           Vec<QueuedOp>,
    flushing:        bool,
    db:              Option<Rc<Rexie>>,
    on_queue_change: Option<js_sys::Function>,
    on_error:        Option<js_sys::Function>,
    on_event:        Option<js_sys::Function>,
    next_seq:        u64,
}

impl Inner {
    fn new(base_url: String) -> Self {
        Inner {
            base_url,
            queue: Vec::new(),
            flushing: false,
            db: None,
            on_queue_change: None,
            on_error: None,
            on_event: None,
            next_seq: 0,
        }
    }

    fn notify_queue_change(&self) {
        if let Some(cb) = &self.on_queue_change {
            let _ = cb.call1(&JsValue::NULL, &JsValue::from(self.queue.len() as u32));
        }
    }

    fn notify_error(&self, msg: &str) {
        if let Some(cb) = &self.on_error {
            let _ = cb.call1(&JsValue::NULL, &JsValue::from_str(msg));
        }
    }

    fn notify_event(&self, event_json: &str) {
        if let Some(cb) = &self.on_event {
            let _ = cb.call1(&JsValue::NULL, &JsValue::from_str(event_json));
        }
    }
}

// ── IDB helpers ────────────────────────────────────────────────────────────────

const IDB_NAME:  &str = "structable_sync";
const IDB_STORE: &str = "ops";

async fn idb_open() -> Result<Rexie, rexie::Error> {
    Rexie::builder(IDB_NAME)
        .version(1)
        .add_object_store(
            ObjectStore::new(IDB_STORE)
                .key_path("op_id")
                .add_index(Index::new("seq", "seq")),
        )
        .build()
        .await
}

async fn idb_put(db: &Rexie, op: &QueuedOp) {
    let tx = match db.transaction(&[IDB_STORE], TransactionMode::ReadWrite) {
        Ok(t) => t,
        Err(_) => return,
    };
    if let Ok(store) = tx.store(IDB_STORE) {
        if let Ok(v) = serde_wasm_bindgen::to_value(op) {
            let _ = store.put(&v, None).await;
        }
    }
    let _ = tx.done().await;
}

async fn idb_delete(db: &Rexie, op_id: &str) {
    let tx = match db.transaction(&[IDB_STORE], TransactionMode::ReadWrite) {
        Ok(t) => t,
        Err(_) => return,
    };
    if let Ok(store) = tx.store(IDB_STORE) {
        let key = JsValue::from_str(op_id);
        let _ = store.delete(key).await;
    }
    let _ = tx.done().await;
}

async fn idb_load_all(db: &Rexie) -> Vec<QueuedOp> {
    let tx = match db.transaction(&[IDB_STORE], TransactionMode::ReadOnly) {
        Ok(t) => t,
        Err(_) => return vec![],
    };
    let store = match tx.store(IDB_STORE) {
        Ok(s) => s,
        Err(_) => return vec![],
    };
    let all = store.get_all(None, None).await.unwrap_or_default();
    let mut ops: Vec<QueuedOp> = all
        .into_iter()
        .filter_map(|v| serde_wasm_bindgen::from_value(v).ok())
        .collect();
    ops.sort_by_key(|o| o.seq);
    ops
}

// ── gRPC client factory ────────────────────────────────────────────────────────

fn grpc_client(base_url: &str) -> GrpcSyncClient<WasmTransport> {
    GrpcSyncClient::new(WasmTransport::new(base_url.to_string()))
}

// ── Flush logic ────────────────────────────────────────────────────────────────

async fn do_flush(inner: Rc<RefCell<Inner>>) {
    // Guard: don't run multiple flushes concurrently
    {
        let mut g = inner.borrow_mut();
        if g.flushing || g.queue.is_empty() {
            return;
        }
        g.flushing = true;
    }

    loop {
        // Peek the first op without holding the borrow across await
        let (base_url, op, db_ref) = {
            let g = inner.borrow();
            if g.queue.is_empty() {
                break;
            }
            (g.base_url.clone(), g.queue[0].clone(), g.db.clone())
        };

        let Some(client_op) = op.clone().into_client_op() else {
            // Malformed op — drop it
            let mut g = inner.borrow_mut();
            g.queue.remove(0);
            g.notify_queue_change();
            continue;
        };

        let mut client = grpc_client(&base_url);
        match client.apply_op(tonic::Request::new(client_op)).await {
            Ok(resp) => {
                let result = resp.into_inner();
                if result.ok {
                    // Persist success: remove from IDB then memory
                    if let Some(db) = &db_ref {
                        idb_delete(db, &op.op_id).await;
                    }
                    let mut g = inner.borrow_mut();
                    g.queue.retain(|q| q.op_id != op.op_id);
                    g.notify_queue_change();

                    // Emit ack as server event
                    let ack_json = serde_json::json!({
                        "ack": { "op_id": op.op_id, "response": result.response }
                    });
                    g.notify_event(&ack_json.to_string());
                } else {
                    // 4xx-style rejection: drop and report
                    if let Some(db) = &db_ref {
                        idb_delete(db, &op.op_id).await;
                    }
                    let mut g = inner.borrow_mut();
                    g.queue.retain(|q| q.op_id != op.op_id);
                    let msg = format!("Op {} rejected: {}", op.op_id, result.error);
                    g.notify_error(&msg);
                    g.notify_queue_change();
                }
            }
            Err(_status) => {
                // Network error — back off and retry
                {
                    let mut g = inner.borrow_mut();
                    if let Some(first) = g.queue.first_mut() {
                        first.retries += 1;
                    }
                    g.flushing = false;
                }
                let inner2 = Rc::clone(&inner);
                wasm_bindgen_futures::spawn_local(async move {
                    TimeoutFuture::new(1_000).await;
                    do_flush(inner2).await;
                });
                return;
            }
        }
    }

    inner.borrow_mut().flushing = false;
}

// ── Enqueue helper ─────────────────────────────────────────────────────────────

async fn enqueue(inner: Rc<RefCell<Inner>>, kind: &str, data: serde_json::Value) -> String {
    let op_id = nanoid::nanoid!();
    let op = {
        let mut g = inner.borrow_mut();
        // Replace any existing op with same logical id (idempotent re-enqueue)
        let logical_id = format!("{kind}:{}", data.get("id").or(data.get("key")).and_then(|v| v.as_str()).unwrap_or(&op_id));
        g.queue.retain(|q| q.op_id != logical_id);

        let seq = g.next_seq;
        g.next_seq += 1;
        let op = QueuedOp { op_id: logical_id.clone(), seq, retries: 0, kind: kind.to_string(), data };
        g.queue.push(op.clone());
        g.notify_queue_change();
        op
    };

    // Persist to IDB (fire-and-forget; crash insurance)
    let db = inner.borrow().db.clone();
    if let Some(db) = &db {
        idb_put(db, &op).await;
    }

    // Kick off flush
    do_flush(Rc::clone(&inner)).await;
    op.op_id
}

// ── Public SyncClient ──────────────────────────────────────────────────────────

#[wasm_bindgen]
pub struct SyncClient {
    inner: Rc<RefCell<Inner>>,
}

#[wasm_bindgen]
impl SyncClient {
    #[wasm_bindgen(constructor)]
    pub fn new(base_url: String) -> SyncClient {
        SyncClient {
            inner: Rc::new(RefCell::new(Inner::new(base_url))),
        }
    }

    /// Open IDB, load any persisted ops, flush them, and start reconnect listener.
    /// Returns a Promise<void>.
    pub fn init(&self) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            match idb_open().await {
                Ok(db) => {
                    let db = Rc::new(db);
                    let stored = idb_load_all(&db).await;
                    let mut g = inner.borrow_mut();
                    g.db = Some(db);
                    // Merge stored ops that are not already in memory
                    let in_memory_ids: std::collections::HashSet<_> =
                        g.queue.iter().map(|o| o.op_id.clone()).collect();
                    let mut max_seq = g.next_seq;
                    for op in stored {
                        if !in_memory_ids.contains(&op.op_id) {
                            max_seq = max_seq.max(op.seq + 1);
                            g.queue.push(op);
                        }
                    }
                    g.queue.sort_by_key(|o| o.seq);
                    g.next_seq = max_seq;
                    g.notify_queue_change();
                }
                Err(e) => {
                    // IDB unavailable (private browsing etc.) — queue is memory-only
                    web_sys::console::warn_1(&JsValue::from_str(
                        &format!("sync_core: IDB unavailable, queue is memory-only: {e:?}"),
                    ));
                }
            }
            // Flush anything already in the queue
            let inner2 = Rc::clone(&inner);
            do_flush(inner2).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    // ── Callbacks ────────────────────────────────────────────────────────────

    pub fn set_on_queue_change(&self, cb: js_sys::Function) {
        self.inner.borrow_mut().on_queue_change = Some(cb);
    }

    pub fn set_on_error(&self, cb: js_sys::Function) {
        self.inner.borrow_mut().on_error = Some(cb);
    }

    /// Register an event callback; called with a JSON string for each ServerEvent.
    /// Returns a `() => void` unsubscribe function.
    pub fn subscribe(&self, on_event: js_sys::Function) -> js_sys::Function {
        self.inner.borrow_mut().on_event = Some(on_event);

        // Start the gRPC Subscribe stream in the background
        let inner = Rc::clone(&self.inner);
        wasm_bindgen_futures::spawn_local(async move {
            loop {
                let (base_url, client_id) = {
                    let g = inner.borrow();
                    (g.base_url.clone(), nanoid::nanoid!())
                };
                let mut client = grpc_client(&base_url);
                let req = tonic::Request::new(SubscribeRequest { client_id });
                match client.subscribe(req).await {
                    Ok(response) => {
                        let mut stream = response.into_inner();
                        loop {
                            match stream.message().await {
                                Ok(Some(event)) => {
                                    if let Ok(json) = serde_json::to_string(&event) {
                                        inner.borrow().notify_event(&json);
                                    }
                                }
                                Ok(None) => break, // stream ended
                                Err(_) => break,   // stream error
                            }
                        }
                    }
                    Err(_) => {}
                }
                // Reconnect after 2s
                TimeoutFuture::new(2_000).await;
                // Stop if on_event was cleared
                if inner.borrow().on_event.is_none() {
                    break;
                }
            }
        });

        // Return a no-op unsubscribe closure (subscriber clears on_event itself if needed)
        js_sys::Function::new_no_args("return undefined")
    }

    pub fn queue_length(&self) -> u32 {
        self.inner.borrow().queue.len() as u32
    }

    // ── Mutation methods ──────────────────────────────────────────────────────

    pub fn upsert_flag(&self, key: String, color: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "upsert_flag", serde_json::json!({ "key": key, "color": color })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    pub fn delete_flag(&self, key: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "delete_flag", serde_json::json!({ "key": key })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    /// Returns Promise<string> — the remark id (either the provided existing_id or a new nanoid).
    pub fn upsert_remark(
        &self,
        existing_id: JsValue,
        kind: String,
        body: String,
        targets_json: String,
    ) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            let id = if existing_id.is_null() || existing_id.is_undefined() {
                nanoid::nanoid!()
            } else {
                existing_id.as_string().unwrap_or_else(|| nanoid::nanoid!())
            };
            let targets: serde_json::Value =
                serde_json::from_str(&targets_json).unwrap_or(serde_json::Value::Array(vec![]));
            enqueue(inner, "upsert_remark", serde_json::json!({
                "id": id, "kind": kind, "body": body, "targets": targets,
            })).await;
            Ok(JsValue::from_str(&id))
        })
    }

    pub fn delete_remark(&self, id: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "delete_remark", serde_json::json!({ "id": id })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    pub fn add_hidden_row(&self, repo_id: f64) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "add_hidden_row", serde_json::json!({ "repo_id": repo_id as i64 })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    pub fn remove_hidden_row(&self, repo_id: f64) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "remove_hidden_row", serde_json::json!({ "repo_id": repo_id as i64 })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    pub fn add_hidden_column(&self, column_id: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "add_hidden_col", serde_json::json!({ "column_id": column_id })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    pub fn remove_hidden_column(&self, column_id: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "remove_hidden_col", serde_json::json!({ "column_id": column_id })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    /// Returns Promise<string> — the column id.
    pub fn create_custom_column(&self, payload_json: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            let mut data: serde_json::Value =
                serde_json::from_str(&payload_json).map_err(|e| JsValue::from_str(&e.to_string()))?;
            if data.get("id").and_then(|v| v.as_str()).unwrap_or("").is_empty() {
                data["id"] = serde_json::Value::String(nanoid::nanoid!());
            }
            let id = data["id"].as_str().unwrap_or("").to_string();
            enqueue(inner, "create_custom_col", data).await;
            Ok(JsValue::from_str(&id))
        })
    }

    pub fn delete_custom_column(&self, id: String) -> js_sys::Promise {
        let inner = Rc::clone(&self.inner);
        future_to_promise(async move {
            enqueue(inner, "delete_custom_col", serde_json::json!({ "id": id })).await;
            Ok(JsValue::UNDEFINED)
        })
    }

    // ── Read methods (returns Promise<string> — JSON) ─────────────────────────

    pub fn fetch_flags(&self) -> js_sys::Promise {
        let base_url = self.inner.borrow().base_url.clone();
        future_to_promise(async move {
            let mut client = grpc_client(&base_url);
            let resp = client.list_flags(tonic::Request::new(ListRequest {})).await
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let json = serde_json::to_string(&resp.into_inner().flags)
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            Ok(JsValue::from_str(&json))
        })
    }

    pub fn fetch_remarks(&self) -> js_sys::Promise {
        let base_url = self.inner.borrow().base_url.clone();
        future_to_promise(async move {
            let mut client = grpc_client(&base_url);
            let resp = client.list_remarks(tonic::Request::new(ListRequest {})).await
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let json = serde_json::to_string(&resp.into_inner().remarks)
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            Ok(JsValue::from_str(&json))
        })
    }

    pub fn fetch_hidden_rows(&self) -> js_sys::Promise {
        let base_url = self.inner.borrow().base_url.clone();
        future_to_promise(async move {
            let mut client = grpc_client(&base_url);
            let resp = client.list_hidden_rows(tonic::Request::new(ListRequest {})).await
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let json = serde_json::to_string(&resp.into_inner().rows)
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            Ok(JsValue::from_str(&json))
        })
    }

    pub fn fetch_hidden_columns(&self) -> js_sys::Promise {
        let base_url = self.inner.borrow().base_url.clone();
        future_to_promise(async move {
            let mut client = grpc_client(&base_url);
            let resp = client.list_hidden_columns(tonic::Request::new(ListRequest {})).await
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let json = serde_json::to_string(&resp.into_inner().cols)
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            Ok(JsValue::from_str(&json))
        })
    }

    pub fn fetch_custom_columns(&self) -> js_sys::Promise {
        let base_url = self.inner.borrow().base_url.clone();
        future_to_promise(async move {
            let mut client = grpc_client(&base_url);
            let resp = client.list_custom_columns(tonic::Request::new(ListRequest {})).await
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let json = serde_json::to_string(&resp.into_inner().cols)
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            Ok(JsValue::from_str(&json))
        })
    }

    pub fn fetch_repos(&self, params_json: String) -> js_sys::Promise {
        let base_url = self.inner.borrow().base_url.clone();
        future_to_promise(async move {
            #[derive(Deserialize)]
            struct Params {
                page:     Option<i32>,
                per_page: Option<i32>,
                sort:     Option<String>,
                #[serde(flatten)]
                filters:  std::collections::HashMap<String, String>,
            }
            let p: Params = serde_json::from_str(&params_json)
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let req = ListReposRequest {
                page:     p.page.unwrap_or(1),
                per_page: p.per_page.unwrap_or(50),
                sort:     p.sort.unwrap_or_else(|| "stars_diff_14d:desc".into()),
                filters:  p.filters,
            };
            let mut client = grpc_client(&base_url);
            let resp = client.list_repos(tonic::Request::new(req)).await
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            let json = serde_json::to_string(&resp.into_inner())
                .map_err(|e| JsValue::from_str(&e.to_string()))?;
            Ok(JsValue::from_str(&json))
        })
    }
}

// ── serde impl for proto types (needed for JSON in read methods) ───────────────
// prost types don't derive serde; add manual impls for the read-response types.

impl serde::Serialize for Flag {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("Flag", 3)?;
        st.serialize_field("id",    &self.id)?;
        st.serialize_field("key",   &self.key)?;
        st.serialize_field("color", &self.color)?;
        st.end()
    }
}

impl serde::Serialize for RemarkTarget {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("RemarkTarget", 2)?;
        st.serialize_field("repo_id",   &self.repo_id)?;
        st.serialize_field("column_id", &self.column_id)?;
        st.end()
    }
}

impl serde::Serialize for Remark {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("Remark", 6)?;
        st.serialize_field("id",          &self.id)?;
        st.serialize_field("body",        &self.body)?;
        st.serialize_field("kind",        &self.kind)?;
        st.serialize_field("is_private",  &self.is_private)?;
        st.serialize_field("resolved_at", &self.resolved_at)?;
        st.serialize_field("targets",     &self.targets)?;
        st.end()
    }
}

impl serde::Serialize for HiddenRow {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("HiddenRow", 2)?;
        st.serialize_field("id",      &self.id)?;
        st.serialize_field("repo_id", &self.repo_id)?;
        st.end()
    }
}

impl serde::Serialize for HiddenCol {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("HiddenCol", 2)?;
        st.serialize_field("id",        &self.id)?;
        st.serialize_field("column_id", &self.column_id)?;
        st.end()
    }
}

impl serde::Serialize for CustomCol {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        let mut st = s.serialize_struct("CustomCol", 6)?;
        st.serialize_field("id",             &self.id)?;
        st.serialize_field("name",           &self.name)?;
        st.serialize_field("label",          &self.label)?;
        st.serialize_field("expression",     &self.expression)?;
        st.serialize_field("position_after", &self.position_after)?;
        st.serialize_field("description",    &self.description)?;
        st.end()
    }
}

impl serde::Serialize for ServerEvent {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeMap;
        let mut map = s.serialize_map(Some(1))?;
        match &self.payload {
            Some(server_event::Payload::Ack(v)) => {
                map.serialize_entry("ack", &serde_json::json!({
                    "op_id": v.op_id,
                    "response": v.response,
                }))?;
            }
            Some(server_event::Payload::Error(v)) => {
                map.serialize_entry("error", &serde_json::json!({
                    "op_id": v.op_id, "message": v.message,
                }))?;
            }
            Some(server_event::Payload::Flag(v)) => {
                map.serialize_entry("flag", &serde_json::json!({
                    "kind": v.kind,
                    "data": v.data.as_ref().map(|d| serde_json::json!({
                        "id": d.id, "key": d.key, "color": d.color,
                    })),
                }))?;
            }
            Some(server_event::Payload::Remark(v)) => {
                map.serialize_entry("remark", &serde_json::json!({
                    "kind": v.kind,
                    "data": v.data.as_ref().map(|d| serde_json::json!({
                        "id": d.id, "body": d.body, "kind": d.kind,
                        "is_private": d.is_private, "resolved_at": d.resolved_at,
                        "targets": d.targets.iter().map(|t| serde_json::json!({
                            "repo_id": t.repo_id, "column_id": t.column_id,
                        })).collect::<Vec<_>>(),
                    })),
                }))?;
            }
            Some(server_event::Payload::HiddenRow(v)) => {
                map.serialize_entry("hidden_row", &serde_json::json!({
                    "kind": v.kind,
                    "data": v.data.as_ref().map(|d| serde_json::json!({
                        "id": d.id, "repo_id": d.repo_id,
                    })),
                }))?;
            }
            Some(server_event::Payload::HiddenCol(v)) => {
                map.serialize_entry("hidden_col", &serde_json::json!({
                    "kind": v.kind,
                    "data": v.data.as_ref().map(|d| serde_json::json!({
                        "id": d.id, "column_id": d.column_id,
                    })),
                }))?;
            }
            Some(server_event::Payload::CustomCol(v)) => {
                map.serialize_entry("custom_col", &serde_json::json!({
                    "kind": v.kind,
                    "data": v.data.as_ref().map(|d| serde_json::json!({
                        "id": d.id, "name": d.name, "label": d.label,
                        "expression": d.expression, "position_after": d.position_after,
                        "description": d.description,
                    })),
                }))?;
            }
            None => {
                map.serialize_entry("unknown", &serde_json::Value::Null)?;
            }
        }
        map.end()
    }
}

impl serde::Serialize for PagedRepos {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        use serde::ser::SerializeStruct;
        // rows_json elements are raw JSON bytes — parse them back so JS gets real objects
        let rows: Vec<serde_json::Value> = self.rows_json.iter()
            .filter_map(|b| serde_json::from_slice(b).ok())
            .collect();
        let mut st = s.serialize_struct("PagedRepos", 4)?;
        st.serialize_field("data",     &rows)?;
        st.serialize_field("total",    &self.total)?;
        st.serialize_field("page",     &self.page)?;
        st.serialize_field("per_page", &self.per_page)?;
        st.end()
    }
}
